### ISSUE TITLE
Add Site Badge

### ISSUE THREAD

**Issue by rjamison** [amzn/amazon-payments-magento-plugin#103]
Seller has requested that we add a site-wide "Accepts Amazon Payments" badge in their footer or sidebar.  Should look at other payment providers and try to match where they place badges.

Resources here:  https://payments.amazon.com/resources

**Comment by jonahellison** [comment]
Example: http://1-8-ap.stage.beargroup.com/

Added to right sidebar (same as PayPal). Note that some themes may exclude the right sidebar.

**Comment by gbear** [comment]
Add a config option to show/hide
