### ISSUE TITLE
Multiple Creditmemos Per Order

### ISSUE THREAD

**Issue by jcymerman** [amzn/amazon-payments-magento-plugin#109]
It appears that the module does not currently support having multiple creditmemos per order, which is a big problem for our client.  Here is the error that is generated when trying to create a second creditmemo for the same order:

![image](https://cloud.githubusercontent.com/assets/10455724/5671445/f633e676-9755-11e4-98cd-b004da1c3572.png)

**Comment by rjamison** [comment]
I think an update of the extension should resolve the issue.  A similar issue was fixed with #90, which was included in the v1.2 release.  Could you give that a go and let us know?

**Comment by jcymerman** [comment]
Ok, thanks, we will update the module tomorrow and see if the issue is fixed!

**Comment by ngrices** [comment]
Closing until further notice
