### ISSUE TITLE
Disable Login with Amazon from customer account page if disabled product in cart

### ISSUE THREAD

**Issue by ngrices** [amzn/amazon-payments-magento-plugin#110]
Currently we have a feature to disable showing the Pay with Amazon button if an item in the cart has the "Disable purchase with Amazon Payments" flag but this in not supressing the Login with Amazon button on the customer/account/login page. This allows the buyer to login with their Amazon account and then see the Amazon checkout even when items in the cart have this flag
Repro:
1) Mark a product with disable Amazon Payments flag
2) Return to store front as non-logged in user
3) add item to cart from step 1
4) Go to customer/account/login
5) Click Login with Amazon and login
6) Return to checkout
7) Widgets are shown in onepage checkout

**Comment by ngrices** [comment]
Maybe the correct behavior is to leave the Login with Amazon button on the customer/account/login page  but force the regular checkout when there are restricted items in the cart.

**Comment by jonahellison** [comment]
Forcing regular checkout when restricted items in cart. Also now hiding "Amazon Payments" radio payment method option for onepage checkouts if restricted items in cart.

**Comment by ngrices** [comment]
whoops...nevermind.
