### ISSUE TITLE
Add Support for Vector Scalable Button

### ISSUE THREAD

**Issue by rjamison** [amzn/amazon-payments-magento-plugin#111]

**Comment by ngrices** [comment]
SVG integration testing not quite ready for implementation in this extension. Will move this to next milestone

**Comment by ngrices** [comment]
Integration for SVG is ready now

**Comment by danielneu** [comment]
Are we talking about the SVG buttons with the current button widget and the parameters width, height and aspectRatio (maybe the exact naming is different)?
If yes, this is incompatible with multi-language buttons in the EU, which will be rolled out end of the month (sandbox already available, just contact me).

~Daniel

**Comment by islandskater43** [comment]
Bumping until we determine how to handle with EU integration.

**Comment by islandskater43** [comment]
Closing for now as this is not currently supported by the Amazon Pay product.
