### ISSUE TITLE
Amazon Login on IP/password protected websites?

### ISSUE THREAD

**Issue by daroPL** [amzn/amazon-payments-magento-plugin#112]
Hi,

I have a Magento EE 1.12.0.2 in a development stage on VPS with only a few IP allowed to access the WWW.
I've installed the latest version (release 1.2.2) of this module and I can't login to Magento using my working Amazon account email and password. It says it's wrong (Amazon message within the login popup), but not.

I tried to login on similar shop (not Magento) and it's working pretty good.

I use default module settings - login in Popup. SSL enabled.

What's is wrong?

Thanks in advance!

**Comment by ngrices** [comment]
Hi there,
Can you click the 'Show Details' in the pop-up error message to get more information?

**Comment by islandskater43** [comment]
It also sounds like you could be trying to log in to the sandbox using
production Amazon credentials. If your plugin settings are set to sandbox
mode for testing, make sure to use a test account. You can create a test
account in Seller Central by selecting the sandbox option in the dropdown
in the top right, then selecting "Test Accounts" from the Integration menu.

**Comment by daroPL** [comment]
@ngrices There is no the 'show details' link. It's a standard error message if e-mail/password is incorrect.
@islandskater43 Yes. I have enabled 'sandbox mode', but it's a setting for Amazon Payments module, not for Amazon Login. and yes, I use production Amazon account e-mail/password.

**Comment by ngrices** [comment]
@daroPL I undertand. @islandskater43's guess about sandbox mode was correct. The flag on the Payments configuration affects the Login with Amazon functionality as well. You can transact in sandbox but will need to create a test buyer account as @islandskater43 mentioned. To use your real Amazon.com buyer account you can switch the Sandbox setting to 'No'

**Comment by daroPL** [comment]
@islandskater43 @ngrices You're right. Disabling sandbox mode fixed the issue. Thanks.
