### ISSUE TITLE
Token payments. Detect cart size over $500

### ISSUE THREAD

**Issue by ngrices** [amzn/amazon-payments-magento-plugin#113]
When the cart is over $500 the UI throws the following stack trace to the buyer. We need a cleaner message. 

exception 'OffAmazonPaymentsService_Exception' with message 'BillingAgreement C01-2024747-3887696 has already been authorized for amount 0.00 in time period i.e. Thu Jan 01 00:00:00 UTC 2015 - Sun Feb 01 00:00:00 UTC 2015. A new authorization with amount 20005.00 cannot be accepted as the total authorization amount cannot exceed 500.00.' in /opt/bitnami/apps/magento/htdocs/lib/OffAmazonPaymentsService/Client.php:914
Stack trace:
#0 /opt/bitnami/apps/magento/htdocs/lib/OffAmazonPaymentsService/Client.php(862): OffAmazonPaymentsService_Client->_reportAnyErrors('<ErrorResponse ...', 400, Object(OffAmazonPaymentsService_Model_ResponseHeaderMetadata))
#1 /opt/bitnami/apps/magento/htdocs/lib/OffAmazonPaymentsService/Client.php(717): OffAmazonPaymentsService_Client->_invoke(Array)
#2 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/Api.php(98): OffAmazonPaymentsService_Client->authorizeOnBillingAgreement(Object(OffAmazonPaymentsService_Model_AuthorizeOnBillingAgreementRequest))
#3 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/Api.php(475): Amazon_Payments_Model_Api->request('authorizeOnBill...', Array)
#4 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/PaymentMethod.php(135): Amazon_Payments_Model_Api->authorizeOnBillingAgreement('C01-2024747-388...', '100000001-14217...', 20005, 'USD', true, 'Default Store V...', NULL)
#5 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/PaymentM...p/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction-…

**Comment by islandskater43** [comment]
To make this the best integration possible, it would be nice if the plugin could check the remaining amount available in the Billing Agreement, as opposed to using the $500 amount. The GetBillingAgreementDetails call will return the remaining balance allowed:

```xml
<BillingAgreementLimits>
  <CurrentRemainingBalance>
    <CurrencyCode>USD</CurrencyCode>
    <Amount>94.50</Amount>
  </CurrentRemainingBalance>
</BillingAgreementLimits>
```

http://docs.developer.amazonservices.com/en_US/off_amazon_payments/OffAmazonPayments_GetBillingAgreementDetails.html

If the cart total is above the currentRemainingBalance, perhaps it could fall back to a regular ORO transaction.

**Comment by rjamison** [comment]
* Let's add a message in the admin console under Enable Tokenized Payments that Buyers can only spend $500 / token.  If they need more, please contact an Amazon account manager.
