### ISSUE TITLE
Tokenized Payments: automatic purchase enabled by default

### ISSUE THREAD

**Issue by ngrices** [amzn/amazon-payments-magento-plugin#114]
The modal ajax checkout window is showing when not logged in as Amazon user or not logged in at all.
Repro:
Admin > System > Payment Methods > AP, Set:
Checkout Page Type = Amazon Stand Alone
Enable Tokenized Payments = Yes
Require Tokenized Payments for Purchases = Yes
Shortcut on Product View = Yes

1) incognito tab
2) browse to product with Pay with Amazon on detail page
3) Click the button

modal pop-up comes up. Clicking button again will take buyer through the pop-up or redirect in the modal window.

**Comment by gbear** [comment]
skip first modal popup from product detail page
- no billing agreement
- not logged in
