### ISSUE TITLE
Sync with Amazon Button (blank page)

### ISSUE THREAD

**Issue by digitalincite** [amzn/amazon-payments-magento-plugin#118]
Recent upgrade Amazon Payments Magento Plugin from 1.1.2 to 1.2.2. When we click on "Sync with Amazon" button on Order details we are directed to a blank page and nothing happens. Any help would be appreciated.

**Comment by rjamison** [comment]
@digitalincite Can you provide a log entry from exception.log?

**Comment by ngrices** [comment]
@digitalincite Also, can you confirm that you have an order that is 'On Hold' that you are attempting to sync?

**Comment by digitalincite** [comment]
Currently, there are no Amazon Payment Orders that have a status of "On Hold".

**Comment by ngrices** [comment]
Are you able to edit your source? I think I have a manual fix or the package update will be available this Friday in Magento connect.

**Comment by digitalincite** [comment]
Yes, we can edit the source.

**Comment by ngrices** [comment]
@digitalincite closing this. Please reopen if this is still an issue for you
