### ISSUE TITLE
Sorry, no quotes are available for this order at this time.

### ISSUE THREAD

**Issue by ckranda** [amzn/amazon-payments-magento-plugin#121]
Select an address with no shipping quotes, then change the address to a valid address in the amazon address widget, then see there are still no shipping quote (in core one page checkout and standalone)- error message above is shown.

**Comment by ngrices** [comment]
Closed with a commit?

**Comment by ngrices** [comment]
@jonahellison Can you comment on this?

**Comment by ckranda** [comment]
hello, this ling didn't lead me anywhere @ngrices can you confirm?

**Comment by ngrices** [comment]
@ckranda this issue is not resolved in the extension and was inadvertently closed the first time. It is in the queue to be fixed in the next development cycle

**Comment by ckranda** [comment]
thank you @ngrices

**Comment by jonahellison** [comment]
Fixed Magento shipping address validation to prevent "sticky" addresses.
