### ISSUE TITLE
Sandbox orders should be identifiable to a merchant 

### ISSUE THREAD

**Issue by ngrices** [amzn/amazon-payments-magento-plugin#122]
The business requirement here is that owners need to be able to id test orders such that they are not accidentally fulfilled. The is quite a bit of feedback from merchants on this one.

Ideas? Is there any information we can add here?

![screen shot 2015-01-26 at 5 23 30 pm](https://cloud.githubusercontent.com/assets/7907929/5911866/4fc7e3a8-a580-11e4-8247-b47f86461c21.png)

**Comment by gbear** [comment]
Add as order comment.
