### ISSUE TITLE
Magemonkey newsletter plugin causes Place order button to fail

### ISSUE THREAD

**Issue by shrakuma** [amzn/amazon-payments-magento-plugin#123]
Mage monkey news letter plugin causes the place order button to not be triggered. This has been a recurring issue with the LPA plugin. The current workaround has been to disable the Mage Monkey plugin .

**Comment by jonahellison** [comment]
MageMonkey was causing a JS error when trying to dynamically add input elements to the payment form. (The Amazon payment form has no form elements, so MageMonkey's JS could not find the correct location to add their input elements.)
