### ISSUE TITLE
Z-Index not respected in widgets

### ISSUE THREAD

**Issue by ngrices** [amzn/amazon-payments-magento-plugin#124]
Example Site: https://www.luggageonline.com/checkout/amazon_payments/
![screen shot 2015-02-05 at 1 30 55 pm](https://cloud.githubusercontent.com/assets/7907929/6069686/4dbfa3f8-ad3b-11e4-850e-24f23842c29d.png)

**Comment by hpz937** [comment]
.nav-container has a low z-index of 12 which happens to be the same as the widget iframe. nav-container z-index of 13 or above fixes issue

**Comment by ngrices** [comment]
Will add to FAQs

**Comment by ngrices** [comment]
added
