### ISSUE TITLE
Defect: Exception thrown during standalone/tokenized

### ISSUE THREAD

**Issue by ngrices** [amzn/amazon-payments-magento-plugin#127]
Configuration
Checkout Type = Amazon Standalone checkout
Asynchronous Mode = Yes
Enable Tokenized Payments = Yes
Require Tokenized Payments for Purchases = No
Allow Pre-Orders = Yes

Repro:
1) Buy something, do not select consent widget

2015-02-16T22:00:01+00:00 ERR (3):
exception 'OffAmazonPaymentsService_Exception' with message 'The number of Order References that could be created on a DRAFT Billing Agreement has exceeded the maximum allowed limit of one Order Reference.' in /opt/bitnami/apps/magento/htdocs/lib/OffAmazonPaymentsService/Client.php:914
Stack trace:
#0 /opt/bitnami/apps/magento/htdocs/lib/OffAmazonPaymentsService/Client.php(862): OffAmazonPaymentsService_Client->_reportAnyErrors('<ErrorResponse ...', 405, Object(OffAmazonPaymentsService_Model_ResponseHeaderMetadata))
#1 /opt/bitnami/apps/magento/htdocs/lib/OffAmazonPaymentsService/Client.php(602): OffAmazonPaymentsService_Client->_invoke(Array)
#2 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/Api.php(98): OffAmazonPaymentsService_Client->createOrderReferenceForId(Object(OffAmazonPaymentsService_Model_CreateOrderReferenceForIdRequest))
#3 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/Api.php(508): Amazon_Payments_Model_Api->request('createOrderRefe...', Array)
#4 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/PaymentMethod.php(267): Amazon_Payments_Model_Api->createOrderReferenceForId('C01-3777106-975...', 'BillingAgreemen...', true, true, Array)
#5 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/PaymentMethod.php(84): Amazon_Payments_Model_PaymentMethod->order(Object(Mage_Sales_Model_Order_Payment), 35)
#6 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Order/Payment.php(334): Amazon_Payments_Model_PaymentMethod->initialize('authorize_captu...', Object(Varien_Object))
#7 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Order.php(886): Mage_Sales_Model_Order_Payment->place()
#8 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Order.php(1104): Mage_Sales_Model_Order->_placePayment()
#9 [internal function]: Mage_Sales_Model_Order->place()
#10 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#11 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#12 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#13 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#14 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/Type/Checkout.php(136): Mage_Sales_Model_Service_Quote->submitAll()
#15 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/controllers/CheckoutController.php(241): Amazon_Payments_Model_Type_Checkout->saveOrder()
#16 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Amazon_Payments_CheckoutController->saveOrderAction()
#17 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#18 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#20 /opt/bitnami/apps/magento/htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#21 /opt/bitnami/apps/magento/htdocs/index.php(87): Mage::run('', 'store')
#22 {main}
2015-02-16T22:00:01+00:00 ERR (3):
exception 'Mage_Core_Exception' with message 'exception 'OffAmazonPaymentsService_Exception' with message 'The number of Order References that could be created on a DRAFT Billing Agreement has exceeded the maximum allowed limit of one Order Reference.' in /opt/bitnami/apps/magento/htdocs/lib/OffAmazonPaymentsService/Client.php:914
Stack trace:
#0 /opt/bitnami/apps/magento/htdocs/lib/OffAmazonPaymentsService/Client.php(862): OffAmazonPaymentsService_Client->_reportAnyErrors('<ErrorResponse ...', 405, Object(OffAmazonPaymentsService_Model_ResponseHeaderMetadata))
#1 /opt/bitnami/apps/magento/htdocs/lib/OffAmazonPaymentsService/Client.php(602): OffAmazonPaymentsService_Client->_invoke(Array)
#2 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/Api.php(98): OffAmazonPaymentsService_Client->createOrderReferenceForId(Object(OffAmazonPaymentsService_Model_CreateOrderReferenceForIdRequest))
#3 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/Api.php(508): Amazon_Payments_Model_Api->request('createOrderRefe...', Array)
#4 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/PaymentMethod.php(267): Amazon_Payments_Model_Api->createOrderReferenceForId('C01-3777106-975...', 'BillingAgreemen...', true, true, Array)
#5 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/PaymentMethod.php(84): Amazon_Payments_Model_PaymentMethod->order(Object(Mage_Sales_Model_Order_Payment), 35)
#6 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Order/Payment.php(334): Amazon_Payments_Model_PaymentMethod->initialize('authorize_captu...', Object(Varien_Object))
#7 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Order.php(886): Mage_Sales_Model_Order_Payment->place()
#8 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Order.php(1104): Mage_Sales_Model_Order->_placePayment()
#9 [internal function]: Mage_Sales_Model_Order->place()
#10 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#11 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#12 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#13 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#14 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/Type/Checkout.php(136): Mage_Sales_Model_Service_Quote->submitAll()
#15 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/controllers/CheckoutController.php(241): Amazon_Payments_Model_Type_Checkout->saveOrder()
#16 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Amazon_Payments_CheckoutController->saveOrderAction()
#17 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#18 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#20 /opt/bitnami/apps/magento/htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#21 /opt/bitnami/apps/magento/htdocs/index.php(87): Mage::run('', 'store')
#22 {main}' in /opt/bitnami/apps/magento/htdocs/app/Mage.php:595
Stack trace:
#0 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/Api.php(102): Mage::throwException(Object(OffAmazonPaymentsService_Exception))
#1 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/Api.php(508): Amazon_Payments_Model_Api->request('createOrderRefe...', Array)
#2 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/PaymentMethod.php(267): Amazon_Payments_Model_Api->createOrderReferenceForId('C01-3777106-975...', 'BillingAgreemen...', true, true, Array)
#3 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/PaymentMethod.php(84): Amazon_Payments_Model_PaymentMethod->order(Object(Mage_Sales_Model_Order_Payment), 35)
#4 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Order/Payment.php(334): Amazon_Payments_Model_PaymentMethod->initialize('authorize_captu...', Object(Varien_Object))
#5 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Order.php(886): Mage_Sales_Model_Order_Payment->place()
#6 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Order.php(1104): Mage_Sales_Model_Order->_placePayment()
#7 [internal function]: Mage_Sales_Model_Order->place()
#8 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#9 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#10 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#11 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#12 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/Model/Type/Checkout.php(136): Mage_Sales_Model_Service_Quote->submitAll()
#13 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/controllers/CheckoutController.php(241): Amazon_Payments_Model_Type_Checkout->saveOrder()
#14 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Amazon_Payments_CheckoutController->saveOrderAction()
#15 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#16 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#17 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#18 /opt/bitnami/apps/magento/htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#19 /opt/bitnami/apps/magento/htdocs/index.php(87): Mage::run('', 'store')
#20 {main}
2015-02-16T22:00:01+00:00 ERR (3):
exception 'Zend_Mail_Protocol_Exception' with message ' is unsupported SSL type' in /opt/bitnami/apps/magento/htdocs/lib/Zend/Mail/Protocol/Smtp.php:144
Stack trace:
#0 /opt/bitnami/apps/magento/htdocs/lib/Zend/Mail/Protocol/Smtp/Auth/Login.php(76): Zend_Mail_Protocol_Smtp->__construct('', '', Array)
#1 /opt/bitnami/apps/magento/htdocs/lib/Zend/Mail/Transport/Smtp.php(198): Zend_Mail_Protocol_Smtp_Auth_Login->__construct('', '', Array)
#2 /opt/bitnami/apps/magento/htdocs/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp->_sendMail()
#3 /opt/bitnami/apps/magento/htdocs/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#4 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/Email/Template.php(468): Zend_Mail->send()
#5 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/Email/Template.php(520): Mage_Core_Model_Email_Template->send('owner@example.c...', 'Owner', Array)
#6 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Checkout/Helper/Data.php(247): Mage_Core_Model_Email_Template->sendTransactional('checkout_paymen...', 'general', 'owner@example.c...', 'Owner', Array)
#7 /opt/bitnami/apps/magento/htdocs/app/code/community/Amazon/Payments/controllers/CheckoutController.php(259): Mage_Checkout_Helper_Data->sendPaymentFailedEmail(Object(Mage_Sales_Model_Quote), 'exception 'OffA...')
#8 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Amazon_Payments_CheckoutController->saveOrderAction()
#9 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#10 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /opt/bitnami/apps/magento/htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /opt/bitnami/apps/magento/htdocs/index.php(87): Mage::run('', 'store')
#14 {main}

**Comment by jonahellison** [comment]
Implemented Matt's solution to explicitly generate a new billing agreement ID on sign in. This workaround only works for the pop-up sign-in, though.
