### ISSUE TITLE
Add support for 5 digit zip codes

### ISSUE THREAD

**Issue by dbrent-amazon** [amzn/amazon-payments-magento-plugin#130]
We have a use case where a seller's shipping calculator breaks when a 9 digit zip code gets passed in. The seller is requesting an option to have the module strip the +4. 

They have temporarily modified app/code/community/Amazon/Payments/Controller/Checkout.php to split on the hyphen if it exists.

I asked if the shipping calculator could be modified but it is not open source and owned by a different company. Seller requesting flexibility in our module.

**Comment by ngrices** [comment]
@dbrent-amazon Feel free to commit that fix of splitting on hyphen if present

**Comment by dbrent-amazon** [comment]
https://github.com/amzn/amazon-payments-magento-plugin/compare/postal-fix?expand=1
