### ISSUE TITLE
Add Sync Auth in front of Async Auth to Reduce Number of Indeterminant Orders

### ISSUE THREAD

**Issue by rjamison** [amzn/amazon-payments-magento-plugin#131]

**Comment by islandskater43** [comment]
This would be really cool if added. This would allow merchants to keep buyers engaged when possible, while still benefiting from the use of Async when necessary! This is one of the main integration patterns we encourage for best overall experience.

**Comment by ngrices** [comment]
Behavior should be:
Merchant has async config
Place Order
Issue sync auth (with optional capture now)
If answer is decline (not TTO), decline order and return to widgets
If answer is decline (TTO) make new async call auth and set order to payment pending
If answer is open auth, move to New Order Status (optionally issue invoice)

**Comment by jonahellison** [comment]
Test TTO with:
{"SandboxSimulation": {"State":"Declined", "ReasonCode":"TransactionTimedOut"}}

In the Order comments, there'll be a comment indicated  the transaction timed out and an async auth was performed.
