### ISSUE TITLE
Add support for 'None' Payment Action

### ISSUE THREAD

**Issue by dbrent-amazon** [amzn/amazon-payments-magento-plugin#132]
We have a seller that is using Cardinal Commerce and the Pay with Amazon module together. The issue is Cardinal needs an order reference ID that has not been authorized prior to reaching them. The Pay with Amazon module doesn't have an option for "None" for Payment Action. When selected it should display a warning that funds can only be captured from a 3rd party system

Requirements:
1) SetOrderReferenceDetails and ConfirmOrderReferenceDetails on ORO
2) Create Order in Magento
3) If this option is selected and 'Pending' or 'Processing' is set the admin should issue a warning saying something to the effect of 'You have set orders to start in a 'Pending' state but not have funds Authorized, you should set the New Order Status to a customer Order Status to identify these orders in your Magento system'
4) When Order is placed it should store the OrderReferenceId and the other order data, perhaps with a -1 or other signal value for the transcationId (AmazonAuthorizationId)

**Comment by rjamison** [comment]
The tokenized payment branch includes support for a new feature "Allow Pre-Orders" that disables authorization of OROs.  Timing is 3-4 weeks until it's release ready.

**Comment by dbrent-amazon** [comment]
How would the authorization occur? Would the seller manually authorize the order when the item ships?

**Comment by ngrices** [comment]
The way the token feature works as implemented today, all orders can be forced to receive a token (BillingAgreementId). This id would be exported to Cardinal where they could perform the auth and subsequent capture

**Comment by ngrices** [comment]
FYI, this functionality is in the token branch but not released in Magento Connect

**Comment by dbrent-amazon** [comment]
Thanks Nathan. I will have to check with Cardinal to see if they accept B01... and C01... billing agreement IDs.

**Comment by ngrices** [comment]
Updated feature request.

**Comment by MannyFarooqi** [comment]
Hi Guys, Any update on this project? We would like to setup Amazon Pay and process though Cardinal commerce as soon as possible :)

**Comment by ngrices** [comment]
@MannyFarooqi Hi Manny, we are slated to deliver the next batch of feature updates at the end of March.

**Comment by bdemps03** [comment]
Thanks for the update!

**Comment by MannyFarooqi** [comment]
@ngrices Hi Nathan, Thanks for the update!

**Comment by ngrices** [comment]
This needs to operate on OrderReferenceIDs and not BillingAgreementIDs

**Comment by jonahellison** [comment]
The Amazon OrderReferenceId is saved as the Magento transaction ID within the order, found in the order comments. When "None" is selected as a Payment Action, the following message is displayed:

*You have set orders to not have funds authorized, so you should set the New Order Status below to a custom status other than "Pending" or "Processing." Funds will need to be captured from a third-party system.*
