### ISSUE TITLE
Disabling "Show Pay with Amazon Button on Cart" removes "Pay with Amazon" button from checkout page

### ISSUE THREAD

**Issue by MichaelThessel** [amzn/amazon-payments-magento-plugin#141]
When I disable "Show Pay with Amazon Button on Cart" the "Pay with Amazon" button disappears from the checkout page too. Without the button users are not able to log in during the checkout process anymore.

**Comment by ngrices** [comment]
@MichaelThessel Can I get a screen shot of the before and after for this to understand?
We will take this for the next sprint to fix
