### ISSUE TITLE
Login button doesn't work on non-SSL pages

### ISSUE THREAD

**Issue by MichaelThessel** [amzn/amazon-payments-magento-plugin#142]
If I try to add the button to a non SSL page the login popup opens with this error message:

> 400 Bad Request
> The domain on which you are using the JavaScript SDK has not been whitelisted for your application.

The error message is misleading too. If I open the same page with SSL enabled the login works just fine. 

I don't think that enforcing SSL here makes sense. As long as the popup and the auth URL are SSL I don't see the need for the button that opens the popup to be on a SSL page as well.

**Comment by islandskater43** [comment]
If any of the pages that the button will be hosted on will be served over HTTP, you must set the Login with Amazon Popup config value to No in your Magento config, and make sure that the Redirect URL is properly set within your Login with Amazon application in Seller Central. That will help avoid the whitelisting error you're getting.

True, the error message could be a little more accurate in this case, stating something like "The URL you are using...", as the domain you've entered could match, while you only have a protocol mismatch.

As for the requirement for the page to be HTTPS, this actually comes from how the OAuth protocol works, specifically regarding the implicit grant which is being used by Login with Amazon here. The result of the successful login in the Amazon pop up results in an access token being passed back to the parent window. Per the OAuth spec, this access token must only be transmitted and stored securely, hence the  HTTPS. [Read more here](http://tools.ietf.org/html/rfc6749#section-10.3). So the requirement for HTTPS for the parent window is really to protect the Access Token.

**Comment by MichaelThessel** [comment]
Thanks for the info. I was under the wrong impression that it uses the secure auth url either way. Switching to non-popup mode solved the problem. Thanks!
