### ISSUE TITLE
Subtotal Doubled after Login with Amazon Payments

### ISSUE THREAD

**Issue by rjamison** [amzn/amazon-payments-magento-plugin#144]
From Magento Connect review...

Debug steps:
1. make a new magento customer account with your Amazon buyer account email. Do a login, logout.
2. AmazonPayment login to this new magento user account. Do a login, logout.
3. finally, login to this new account again with your email in magento. DON't logout.
4. add any items to your shopping cart, you will see all subtotals are doubled.
please fix this serious bug. Thank you

**Comment by jjone** [comment]
Great! you fixed it!

**Comment by jjone** [comment]
Not fixed yet. just tried new codes today. Subtotal still doubles or triples.
