### ISSUE TITLE
multiple language site exception, works only in English, 

### ISSUE THREAD

**Issue by jjone** [amzn/amazon-payments-magento-plugin#148]
Hi, 

This is a exception error if i do amazon payment in a chinese language version of my site.

exception 'OffAmazonPaymentsService_Exception' with message 'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.' in /var/www/clients/client1/web1/web/lib/OffAmazonPaymentsService/Client.php:914 Stack trace: #0 /var/www/clients/client1/web1/web/lib/OffAmazonPaymentsService/Client.php(862): OffAmazonPaymentsService_Client->_reportAnyErrors('Justin 

Please fix this bug. Thank you very much

Justin

**Comment by jjone** [comment]
Here is the full exception log, Thank you.

exception 'OffAmazonPaymentsService_Exception' with message 
'The request signature we calculated does not match the signature you provided. 

Check your AWS Secret Access Key and signing method. Consult the service documentation for details.' in 

/var/www/lib/OffAmazonPaymentsService/Client.php:916 Stack trace: #0 
/var/www/lib/OffAmazonPaymentsService/Client.php(862): OffAmazonPaymentsService_Client->_reportAnyErrors() #1 
/var/www/lib/OffAmazonPaymentsService/Client.php(510): OffAmazonPaymentsService_Client->_invoke() #2 
/var/www/app/code/community/Amazon/Payments/Model/Api.php(99): OffAmazonPaymentsService_Client->authorize() #3 
/var/www/app/code/community/Amazon/Payments/Model/Api.php(169): Amazon_Payments_Model_Api->request() #4 
/var/www/app/code/community/Amazon/Payments/Model/PaymentMethod.php(130): Amazon_Payments_Model_Api->authorize() #5 
/var/www/app/code/community/Amazon/Payments/Model/PaymentMethod.php(266): Amazon_Payments_Model_PaymentMethod->_authorize() #6 
/var/www/app/code/community/Amazon/Payments/Model/PaymentMethod.php(84): Amazon_Payments_Model_PaymentMethod->order() #7 
/var/www/app/code/core/Mage/Sales/Model/Order/Payment.php(334): Amazon_Payments_Model_PaymentMethod->initialize() #8 
/var/www/app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place() #9 
/var/www/app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment() #10 
/var/www/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): Mage_Sales_Model_Order->place() #11 
/var/www/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks() #12 
/var/www/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save() #13 
/var/www/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder() #14 
/var/www/app/code/community/Amazon/Payments/Model/Type/Checkout.php(136): Mage_Sales_Model_Service_Quote->submitAll() #15 
/var/www/app/code/community/Amazon/Payments/controllers/CheckoutController.php(235): Amazon_Payments_Model_Type_Checkout->saveOrder() #16 
/var/www/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Amazon_Payments_CheckoutController->saveOrderAction() #17 
/var/www/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch() #18 
/var/www/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match() #19 
/var/www/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch() #20 /var/www/app/Mage.php(684): Mage_Core_Model_App->run() #21 
/var/www/index.php(87): Mage::run() #22 {main}

**Comment by ngrices** [comment]
@jjone Can you tell me what the Seller Note field was? It is possible we dont support Chinese characters

**Comment by jjone** [comment]
Hi, ngrices
Where do i find the Seller Note field?  Thank you.
Justin

**Comment by jonahellison** [comment]
Confirmed that the SoftDescriptor field does no support Chinese characters (@ngrices add to FAQ?). In 1.4.1 the SoftDescriptor can be changed in the admin. Prior versions can modify: app/code/community/Amazon/Payments/Model/PaymentMethod.php and change _getSoftDescriptor() to return plain text instead of the store name.
