### ISSUE TITLE
Refund Acts Against Authorzation NOT capture- throws error

### ISSUE THREAD

**Issue by ckranda** [amzn/amazon-payments-magento-plugin#149]
exception 'OffAmazonPaymentsService_Exception' with message 'The TransactionId P01-2077891-1111111-A222222 is invalid.' in /www/sites/www.seller1.com/files/html/lib/OffAmazonPaymentsService/Client.php:914 Stack trace: 
This forces seller to refund in seller central AND magento for their book keeping processes. This has happened twice to one of our sellers who has no other issues in magento.

Unique conditions-  they are a multi-store seller and this transaction was from one of their child-sites, where all of their sites live under one seller account.

**Comment by ngrices** [comment]
@jonahellison @gbear Can you guys triage this one and think of how this would happen in our code, where we send the auth id instead of the capture id?
Ancillary information: the capture call took almost 1.5 hrs to move to Approved. Could this be an instance where the capture id was never stored?

**Comment by ngrices** [comment]
@jonahellison @gbear Also found out this order was Auth/Capture but async. Maybe cron never updated and received the capture id?

**Comment by ckranda** [comment]
the seller is still seeing the error with sync enabled. 
thank you @jonahellison @ngrices

**Comment by jonahellison** [comment]
Resolved with #152. Future async invoices will save the Capture ID to the invoice instead of the Auth ID.
