### ISSUE TITLE
Support One Step Checkout

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-plugin#150]
One step checkout doesn't seem to work properly with the Pay with Amazon plugin, preventing customers using the one step checkout option from being able to pay using their Amazon account.

**Comment by bkbeltgal** [comment]
I have the same issue!

**Comment by TinyRocket** [comment]
Could you guys clarify which one step checkout you're using (Aheadworks, MageStore, etc)? Right now, I believe that there is only direct support for Firecheckout and IWD OnePage, but adding support for additional checkouts is worth exploring.

**Comment by islandskater43** [comment]
I wasn't aware there were multiple checkout plugins with the same name. I may need to do more research to find out what plugin is more popular. @bkbeltgal - which plugin are you using?

I've made a fix to support the One Step Checkout available at http://www.onestepcheckout.com/  If that is the plugin you have, reach out to me and I'll share the fix so that we can try and test it.

**Comment by bkbeltgal** [comment]
yes... http://onestepcheckout.com/ is the one we have. Thank you!

**Comment by islandskater43** [comment]
@bkbeltgal Can you try the above change and see if it works for you?

**Comment by bkbeltgal** [comment]
It works!!! Thank you so much! Now the issue I have is we want to turn off the Amazon button on the Shopping Cart and just have it as a Payment Method of our OneStepcheckout. Is that possible? The reason is we need to have Customers be able to Submit Order Comments and Special Instructions. Thank you!!!

**Comment by ngrices** [comment]
@islandskater43 Can you create the pull request?

**Comment by islandskater43** [comment]
done. 

@bkbeltgal - can you try commenting out / removing lines 17 - 50 of the same amazon_payments.xml file and see if that removes it from your cart?

**Comment by bkbeltgal** [comment]
Awesome... yes thank you again!
