### ISSUE TITLE
New order associated to different customer

### ISSUE THREAD

**Issue by faisal90** [amzn/amazon-payments-magento-plugin#153]
Hello guys,

Version: 0.1.0
Any known issues about order processed via amazon being associated to a different user's/customers account? This has happened in our store twice.

Any help would be appreciated.

Thanks.

**Comment by ngrices** [comment]
@faisal90 Can you describe the problem in more detail? Are you talking about the shipping/billing address stored in an order, or the top level customer account associated with the order?

**Comment by faisal90** [comment]
No, I am talking about the top level customer account that is associated with an order. However, shipping / billing address remains correct.

e.g. Customer X ordered something and in the system the order is created with the correct shipping/billing information however its associated to Customer Y's account.

**Comment by ngrices** [comment]
Is there a chance you have repro steps for this error?

**Comment by faisal90** [comment]
Unfortunately not; I can't reproduce this but I have experienced this at least 3 times. :(

**Comment by ngrices** [comment]
@faisal90 Closing for now, reopen when we can get a repro. This is a big one if we can get to the bottom of it. I have talked to our integration and support teams and no one has seen this on other merchants side
