### ISSUE TITLE
UK Configuration. Login button points to US endpoint

### ISSUE THREAD

**Issue by ngrices** [amzn/amazon-payments-magento-plugin#154]
Multiple stores configured under one instance of Magento, top level is US, 2nd store is UK. Login button at customer/account points to the US endpoint. Clicking button results in exception being thrown

Error Summary
400 Bad Request
Unknown client_id

**Comment by jonahellison** [comment]
Added Region support for Amazon_Login module.

Like the Client ID setting, the Amazon_Payments module will now "clone" and use the same region value from the Amazon_Login config. (For EU testing, make sure to update the Payments/Region config when pulling this latest code.)
