### ISSUE TITLE
Widgets clickable after order placement

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-plugin#156]
Hi,

For the checkouts that show the widgets in edit mode when the "Place order" button is accessible:

It is possible to change addresses and payment methods after clicking the place order button. There should be for example an overlay that prevents this.

Daniel

**Comment by ngrices** [comment]
Show modal 'Placing order' that restricts access to widgets

**Comment by jonahellison** [comment]
Widgets now restricted (opacity+spinner) when "Place Order" is clicked.

**Comment by danielneu** [comment]
Hi,

I can see opacity + spinner. But I can still change the address and / or  payment method.
It should not be possible to change any detail of the order after it was placed.

It is also possible to change the shipping method, which also has influence on the price and results in different order values in Magento and our systems.

~Daniel

**Comment by jonahellison** [comment]
Updated disable method to use div overlay on widgets and shipping method instead of CSS3.
