### ISSUE TITLE
Issues in decline workflow with synchronous authorization 

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-plugin#157]
Hi,

when using the synchronous authorization and simulating a decline, only the wallet widget should be clickable to change the payment method.
Currently the whole page is active which leads to following behavior:

Address widget:
clicking here leads to an error in the widget, the wallet widget keeps rendering and rendering

Shipping method:
a) change from expensive to cheap:
=> order in our system is placed with higher amount than in Magento, authorization is done for the lower amount. Example: A31WQO0SDD8AN4, S02-5648834-3571307
b) change from cheap to expensive:
=> exception when authorizing the higher amount, see screenshot attaches.

Daniel
![crash_bear](https://cloud.githubusercontent.com/assets/10086275/7113477/8fb4d42c-e1d4-11e4-96c0-ccaa6046fc1d.png)

**Comment by ngrices** [comment]
@gbear The intention here should be to 
1) restrict modifications to the address widget if declined.
2) restrict modifications to shipping if declined

**Comment by danielneu** [comment]
Hi,

I can still change the details as before.
There is now a modal view + spinner, but I can still change my address and the shipping options.

For the address widget, you could switch to the read-only one here or ad a div like in #156

**Comment by danielneu** [comment]
Hi Jonah,

this is working now, but there is still another small issue:

If you get a synchronous decline and you do not change the payment method there is an Exception telling me, that the order has a constraint of paymentPlanNotSet
![sync decline](https://cloud.githubusercontent.com/assets/10086275/8475777/ccc7ecbc-20ba-11e5-81ee-a5b273a99aa9.png)

~Daniel

**Comment by jonahellison** [comment]
Removed exception message.
