### ISSUE TITLE
Decline handling / user interaction not taken into account

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-plugin#158]
Hi,

if we have a decline for an asynchronous authorization, the user has the possibility to change his payment method again on payments.amazon.xx
By doing so, the state of the Order changes from Suspended to Open again, the order then can be authorized again.

The plugin doesn't take this into account:

* The state of the order stays at On-hold
* No new authorization is done

The merchant basically only has the chance to leave his backend and use seller central / scratchpad here.

Daniel

**Comment by ngrices** [comment]
I think we already addressed this, give me a moment to research

**Comment by danielneu** [comment]
I can surely provide more information, if needed.

A workflow that really proved working well is:

auth decline due to InvalidPaymentMethod 
-> send a mail to the customer and move the order On-hold 
-> customer changes the payment method 
-> IPN / polling for ORO goes from suspended back to open
-> authorize

auth decline due to AmazonRejected
-> send a mail to the customer change state of the order

Best,
Daniel

**Comment by jonahellison** [comment]
The current workflow is that the seller must manually click "Sync with Amazon" on the order page to re-authorize. IPN would need to be implemented to automate this. (It wouldn't be efficient for the Mage cron to make a call to the Amazon service for each "On Hold" order.)

Another idea is to email the user a link to their Magento order details page and embed the Wallet Widget here for updating the payment method (I've been doing this for testing). The order state would then "reset" back to pending payment and the cron would attempt another authorize.

**Comment by danielneu** [comment]
Hi,

I just checked this as well. I think this comes down to multiple steps, the first and most crucial one is letting the customer know what is happening. Currently the customer get's redirected to the Thank You page and receives an order confirmation. Additionally he receives an email from Amazon, informing him about the order he has placed.

There is no information about the decline, so there is no reason for the customer to react.

Missing this functionality the "Sync with Amazon" button is nice, but unless the merchant calls the customer, mails him manually, ... there will be no need to issue a new authorization. It will still be the declined payment method in our systems.

If we had something like automated emails and the customer was aware of the situation and actually changes the payment method, how will the merchant know? He will have to check all on-hold orders, open them up and press "Sync with Amazon". 

I like the idea of sending the customer back to the shop but I am not sure if there are time limits in place or if this would also work after, let's say 2 days. But this could really be a good option to "let the merchant know" what happened, without polling for the order status. But even the polling is something that is doable. I tested your suggested solution and it seems to work, even across sessions and browsers (as long as the order is suspended).

@islandskater43 have you done something like this yet

But in general there are more asynchronous operations like Capture and Refund, I don't think we can get rid of doing more with the cron or having IPN support.

~Daniel

**Comment by jonahellison** [comment]
Test Workflow:
- Place order with async enabled and InvalidPaymentMethod sandbox simulation
- Run cron or click "Sync with Amazon" in admin order page (automated email will be sent out with link to order details URL)
- Visit customer order page and select new payment method and click 'Update Order.' This will confirm and attempt a synchronous authorization

**Comment by danielneu** [comment]
Hi Jona,

I like this! This will be one of my favorite features and I think we could reuse this workflow for other plugins as well.
I do have a remark, though:

This only works if the customer logs in with Amazon, but he is directed to the normal log in page and doesn't know about it. Using the default log in procedure of the shop should not be changed in my opinion, but we should point the customer to the fact that he has to log in via Amazon (maybe with the mail text).

If I log in via a normal account I see the widget with a "session timed out" message ans a "Pay with Amazon" button. This should be a "Login with Amazon" button in my eyes. We could also suppress the widget and display a meaningful sentence here.

Thanks,
Daniel
