### ISSUE TITLE
Billing address not used

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-plugin#159]
Hi,

when creating an order, the billing address is set to the selected delivery address. Even after the authorization was successful, this doesn't change.

The expected behavior would be to have the billing address here after an successful authorization, which one can get via getAuthorizationDetails.

Daniel

**Comment by ngrices** [comment]
@danielneu Is getAuthorizationDetails() the only way to get the VAT address (billing address)? We were under the impression that it is returned with GetORODetails as well.

**Comment by danielneu** [comment]
It's the usual way to get it, which means, it is a way to get it which works with all accounts.
Another method is to use the scope payments:billing_address, then it is also retrievable via getORODetails, but this needs whitelisting per account at the moment. I need to check when we can get rid of this.

**Comment by danielneu** [comment]
Addendum:
If we go for the scope version, it should be added as a default scope, not an additional one which can be added via the "Login with Amazon" configuration (additional scopes).

Disabling Login with Amazon would then break the behavior for the pay only version.

**Comment by islandskater43** [comment]
@danielneu Can you explain why the billing address is passed in the AuthorizationResponse, and not earlier in the flow?

**Comment by danielneu** [comment]
@islandskater43 This is because the billing address itself is assigned to the payment method of the customer. It is retrievable only after a successful authorization, thus via the AuthorizationResponse (by default).
As I said, there is also a way to get it after a customer has selected a payment method in our widgets. This needs a special scope, payments:billing_address, and whitelisting per merchant. At least this is the case in the EU. We are discussing to get the need for whitelisting removed. I will loop you into the conversation.

~Daniel

**Comment by jonahellison** [comment]
Using GetAuthorizationDetails to update order billing address after authorize request.

**Comment by danielneu** [comment]
Hi Jonah,

please have a look at my inline comments in the fix.

Daniel

**Comment by jonahellison** [comment]
Updated to include addressLine3 and set billing address for non-US regions (getAuthorizationBillingAddress did not return a billing address for the US).

**Comment by danielneu** [comment]
Looking good, thanks a lot.

**Comment by snoroozi** [comment]
So us billing address being passed to the Magento orders yet? This gets our users all bent out of shape.
