### ISSUE TITLE
Placement of Login Button on Account Page

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-plugin#160]
When viewing the Login or Create an Account page, the Login with Amazon button shows up near the bottom of the page. 

Let's look into if we can improve button placement.

![loginpage](https://cloud.githubusercontent.com/assets/1476371/7309752/4ac6dc9c-e9d7-11e4-86d1-645e3fe7d910.png)

**Comment by ngrices** [comment]
When div containing other sign in methods is large, the button is pushed to the bottom of the page. Perhaps append to end of left hand column.
Change '- OR -' to 'Have an Amazon account?'

**Comment by ngrices** [comment]
@jonahellison move to above block

**Comment by jonahellison** [comment]
Updated Amazon button to appear above login blocks. The "Login or Create an Account" header is part of the login template file, so the button is appearing above that. Another alternative is to place it within the login form (as the template allows additional blocks here). Screen shots:

![amazon_login_top](https://cloud.githubusercontent.com/assets/1158920/14181820/895e32c6-f71d-11e5-8275-cbb4a3fe0c72.PNG)

![amazon_login](https://cloud.githubusercontent.com/assets/1158920/14181829/97e05982-f71d-11e5-8aa8-9aafb9d0f040.PNG)

**Comment by jonahellison** [comment]
To move back to bottom, open amazon_payments.xml and replace customer_account_login section with:

```
    <customer_account_login translate="label">

        <block type="amazon_payments/login_script" name="amazon_login.script" template="amazon_payments/login/script.phtml" />
        <block type="amazon_payments/login_button" name="amazon_login.button_login" template="amazon_payments/login/button.phtml" before="content" />

        <!-- ifconfig only works with action -->
        <reference name="after_body_start">
            <action method="append" ifconfig="payment/amazon_payments/enabled">
                <block>amazon_login.script</block>
            </action>
        </reference>

        <reference name="content">
            <action method="append" ifconfig="payment/amazon_payments/enabled">
                <block>amazon_login.button_login</block>
            </action>
        </reference>
    </customer_account_login>
```
