### ISSUE TITLE
In Magento "Amazon Standalone Checkout" - If not payment method is associated with the Shipping Address - you can still "Place Order" and it surfaces an exception on the page.

### ISSUE THREAD

**Issue by amznmode** [amzn/amazon-payments-magento-plugin#162]
Steps to reproduce - 

1. On a magento merchant using LPA's Amazon Standalone Checkout flow - Pay with Amazon and select/add an Address with No Credit card associated with that address. The Place Order button will still render.
2. Hit the Place Order button. 

![image](https://cloud.githubusercontent.com/assets/8633616/7459561/c67956bc-f251-11e4-9daa-ba1843cbe02d.png)

**Comment by ngrices** [comment]
Disable the Place Order button until the onPaymentSelect event is fired

**Comment by islandskater43** [comment]
To test this, you need to have the plugin in Production/Live mode, as you can't reproduce a no payment methods on file scenario in Sandbox.

**Comment by jonahellison** [comment]
The "Place Order" pane will now be disabled when no payment method is select.
