### ISSUE TITLE
Plugin doesn't provide the site with shipping information

### ISSUE THREAD

**Issue by P3Logic** [amzn/amazon-payments-magento-plugin#165]
Our client utilizes the pay with amazon and when they select an address and credit card, the plugin does not provide the site with the shipping information and the checkout cannot proceed. This requires the client to restart and make an account with the site for the shipping info to populate. Are there any solutions to this problem?

**Comment by ngrices** [comment]
@P3Logic The shipping address is captured from the address book widget and passed to the magento backend for shipping and tax calculation, where the order quote object is created and the order review object is passed back to the front end showing the total. I am guessing you have some sort of extension conflict or possibly the shipping rules need tweaking for the addresses you are testing with. 
Can you contact me directly at ngrice@amazon.com so we can work through your issue?
