### ISSUE TITLE
Use shipping address from Magento Quote 

### ISSUE THREAD

**Issue by ihabz** [amzn/amazon-payments-magento-plugin#166]
Hi There, 

Is there anyway to use the shipping address from Magento quote instead of address from Amazon account when saving the order.  I tried to achieve this by comment 
```javascript
$this->_saveShipping();
```
under reviewAction() in CheckoutController.php but it will just save the default shipping and billing address from customer account. 

Thanks.

**Comment by ngrices** [comment]
@ihabz Doing this will invalidate the Amazon fraud protection since you will not be shipping to the address selected in the widget. I am assuming you are talking about the Shipping Address stored in the order?

**Comment by ihabz** [comment]
@ngrices thanks for your response. yes i am talking about shipping address from  I am only showing Amazon Payments as a Payment option under Payment methods section. because customer must go over the default magento checkout process to get customized shipping methods and prices. My question now can we push the Shipping address from Magento quote and save it to Amazon account when customer select Amazon as payment option and the shipping address does not exist under the customer Amazon account ?  this way the customer does not have to enter the address on Amazon widget.

**Comment by ngrices** [comment]
So you are looking for an API method to push addresses into the Amazon Address Book? If so, no functionality for that exists today and buyers must either add via the widget or log into their amazon.com account and add an address.
