### ISSUE TITLE
Add multi-language support for the EU

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-plugin#171]
Hi,

we are launching a new feature called multi language in the EU this month.
Sandbox access is available starting on the 15th, general availability is planned for the 30th in the live environment.

There is a multi language addendum to the integration guide which I can supply, basically it comes down to:

- add another parameter (language) to the JS of the button widget
```javascript
 var authRequest;
    OffAmazonPayments.Button("AmazonPayButton", "YOUR_SELLER_ID_HERE", {
      type: "PwA",
      language: language, // one of de-DE, en-GB, es-ES, it-IT, fr-FR
      authorization: function() {
      loginOptions = {
        scope: "ENTER_SCOPES", ENTER_POPUP_PARAMETER};
        authRequest = amazon.Login.authorize (loginOptions,
        "YOUR_REDIRECT_URL_HERE");
      },
      onError: function(error) {
        // your error handling code
      }
    });
````
Popup, Consent, Widgets, E-Mails will then be in this language (unless the buyer changes it again, which he is able to do in the popup window).

The getORODetails will then also return the language the order was placed in, which could be used for further communications regarding this order (e.g. automated mails for async auth declines).

**Comment by gbear** [comment]
Want to use base region/language setting in Magento, provide an admin text field that can be used as an override.  Provide a link to reference doc of available languages.

**Comment by danielneu** [comment]
Here is the link to the official documentation: https://payments.amazon.co.uk/developer/documentation/lpwa/201749840#201749950

**Comment by danielneu** [comment]
Here is the same link for the German doumentation:
https://payments.amazon.de/developer/documentation/lpwa/201749840#201749950

**Comment by jonahellison** [comment]
The default locale is under General->Locale Options->Locale (will use de, fr, it, or es)

**Comment by danielneu** [comment]
HI Jonah,

could we adjust the link to the documentation depending on the country?
The guides are pretty similar, but there are things which are allowed in UK but not in Germany (auto-payments e.g.). SHowing the correct documentation depending on the country would be great.
UK: https://payments.amazon.co.uk/developer/documentation/lpwa/201749840#201749950
DE:https://payments.amazon.de/developer/documentation/lpwa/201749840#201749950

**Comment by jonahellison** [comment]
German link now localized.

**Comment by danielneu** [comment]
Seems not to work.
See current screenshot
![wrong_url](https://cloud.githubusercontent.com/assets/10086275/8501332/b163a782-21a4-11e5-838d-e1ac548a733a.png)

**Comment by danielneu** [comment]
Hi,

I also found something else that seems not to be working as expected.
* enter e.g. es-ES to the textfield
* click save
=> Button is Spanish
* check the box "Use Default"
* click save
=> Button stays Spanish

I would expect the setting from a higher scope to kick in (which is empty -> default locale).

Thanks,
Daniel
