### ISSUE TITLE
Add Pay with Amazon Option in Mini cart

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-plugin#174]
It would be ideal to add the Pay with Amazon button into the mini cart in the header like Paypal does.

**Comment by islandskater43** [comment]
Detect if current page is HTTPS, if yes - follow popup setting, otherwise, fall back to redirect.

**Comment by rjamison** [comment]
Likely the merchant is going to run into issues with redirect URL settings in Login if we switch to redirect automatically.  This change should also include updating the main configuration page with advice for setting this:

Please add these URLs in Seller Central under "Allowed Return URLs":

https://website.url/amazon_login/customer/authorize/
https://website.url/amazon_payments/checkout/authorize/
