### ISSUE TITLE
Review async decline text for customer emails and wallet widget

### ISSUE THREAD

**Issue by jonahellison** [amzn/amazon-payments-magento-plugin#177]
See #158

- Review email subject and body text (using the standard Magento email template: Dear Customer ... [body text] ... If you have any questions...) -- https://github.com/amzn/amazon-payments-magento-plugin/blob/master/app/locale/en_US/template/email/amazon_payments_async_decline.html

- Review text above Wallet Widget on order details page -- https://github.com/amzn/amazon-payments-magento-plugin/blob/master/app/design/frontend/base/default/template/amazon_payments/sales/order/amazon_wallet.phtml

- Review error and success messages

**Comment by ngrices** [comment]
@islandskater43 can you close on this by 8/19. I want to work on the Magento release starting 8/20

**Comment by islandskater43** [comment]
Yes - will work to resolve by 8/19.

**Comment by islandskater43** [comment]
Reviewed and confirmed verbiage is good as is.
