### ISSUE TITLE
Password send in plain text on account creation

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-plugin#178]
Hi,

when logging in for the first time the generated password is send out in plain text with the confirmation mail. Is this configurable in Magento? 

I don't think that this is something merchants in Europe would allow.

Thanks,
Daniel

**Comment by rjamison** [comment]
That's the default functionality of Magento, not modified by our extension.  The merchant would need to modify the default email template to exclude the password.
