### ISSUE TITLE
Backend not localized

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-plugin#179]
Hi,

all links in the backend lead to the us seller central.
There is a different one for the EU: http://sellercentral-europe.amazon.com/

Magento Administration :-

1.	Magento Admin -> Payment Methods -> Login to Get Your Keys
- Opens url to sellercentral.amazon.com (US, not region specific)

2.	Magento Admin -> Payment Methods -> Add your url to "Allowed Javascript Origins"
- Opens url to sellercentral.amazon.com (US, not region specific)

Best,
Daniel

**Comment by jonahellison** [comment]
Added two checks for localization (either/or will trigger link change):

1. If Amazon Payments "Region" set to Germany or UK
2. If country is in Europe under General->Locale Options->Locale
