### ISSUE TITLE
No Login button on Checkout page

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-plugin#180]
Hi,

when deciding to use "Procced to checkout" there is no "Login with Amazon" button.
As the user is requested to log in and "Login with Amazon" is a valid method to do so, there should be a button as well.

~Daniel

**Comment by islandskater43** [comment]
Include comment on how to disable.

**Comment by jonahellison** [comment]
Updated "Login with Amazon" to display for Standalone Checkout on OnePage checkout page.

Added comment in amazon_payments.xml layout file on how to remove (under <reference name="checkout.onepage.login">)
