### ISSUE TITLE
Close an order if fully captured

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-plugin#181]
Hi,

if an order is fully captured, we could close the ORO on our side, which is a better experience for merchants and customers.
Merchants can see the correct state in seller central, customers can see that an order was processed in the YAUI on payments.amazon.xxx.

I think this behavior ( if(orderAmount == capturedAmount){ capture(ORO);} ) would fit for nearly all merchants. We could also make this behavior configurable.

Best wishes
Daniel

**Comment by danielneu** [comment]
Another possibility would be to add the close call to the actual shipment

**Comment by jonahellison** [comment]
Added close call when Magento order state is changed to COMPLETE (can occur when "Ship" is clicked).
