### ISSUE TITLE
Pages don't obey plugin disabled setting

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-plugin#183]
Files /app/design/frontend/base/default/template/amazon_payments/script.phtml and /app/design/frontend/base/default/template/amazon_login/script.phtml don't obey when the plugin is disabled.

This could be that the plugin is enabled, but disabled for an individual store.

**Comment by jonahellison** [comment]
I can't repo this... do you have repo steps? If this issue is from the 1.3 release, then it's resolved as these templates were updated to check if the plug-in is enabled.

**Comment by ngrices** [comment]
@islandskater43 are we moving this to the next milestone?
