### ISSUE TITLE
Mixed Content warning on cart page

### ISSUE THREAD

**Issue by dbrent-amazon** [amzn/amazon-payments-magento-plugin#184]
Chrome shows the following warnings on the cart page when secure cart is enabled.

Mixed Content: The page at 'https://www.example.org/magento/index.php/checkout/cart/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://www.example.org/magento/index.php/checkout/cart/couponPost/'. This endpoint should be made available over a secure connection.

Mixed Content: The page at 'https://www.example.org/magento/index.php/checkout/cart/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://www.example.org/magento/index.php/checkout/cart/estimatePost/'. This endpoint should be made available over a secure connection.

This causes the secure lock icon to have a yellow triangle which may make a buyer uncomfortable making a purchase. Enabling secure front-end does not fix.

![screen shot 2015-07-15 at 9 48 29 am](https://cloud.githubusercontent.com/assets/9828472/8704251/bc4a2906-2ad6-11e5-8dfd-602a83798ae8.png)

There is a workaround. Setting Unsecure Base URL to https will make these warning go away. Can we force the endpoints in question to https when secure cart is enabled?

**Comment by tinyrocket** [comment]
The quickest solution is to modify the action for the Coupon and Shipping Estimation forms inside of their respective templates. 

For the coupon **(app/design/frontend/YOUR-THEME/template/checkout/cart/coupon.phtml)**, change the form action to: 

    <?php echo $this->getUrl('checkout/cart/couponPost', array('_secure' => true)) ?>

For the shipping estimation **(app/design/frontend/YOUR-THEME/template/checkout/cart/shipping.phtml)**, change the form action to: 

    <?php echo $this->getUrl('checkout/cart/estimatePost', array('_secure' => true)) ?>

A more long term solution would be to add these two URL's to the **secure_url** node inside of 

    app/code/community/Amazon/Payments/etc/config.xml

**Comment by ngrices** [comment]
@tinyrocket Thanks for the tip! I will make a pull request. Can you maybe review?

**Comment by ngrices** [comment]
Including in 1.3.1 release

**Comment by ngrices** [comment]
@tinyrocket in the config.xml file the tags for secure urls are named
 <frontend>
        <secure_url>
            <cart_updatepost>/checkout/cart/updatePost</cart_updatepost>
            <checkout_amazon>/checkout/amazon_payments</checkout_amazon>
            <amazon_checkout>/amazon_payments/checkout</amazon_checkout>
        </secure_url>

does the naming of the xml element reflect in lookups? or could I just add the two lines and choose the names ad hoc

 <frontend>
        <secure_url>
            <cart_updatepost>/checkout/cart/updatePost</cart_updatepost>
            <checkout_amazon>/checkout/amazon_payments</checkout_amazon>
            <amazon_checkout>/amazon_payments/checkout</amazon_checkout>
            <cart_couponpost>/checkout/cart/couponPost</cart_couponpost>
            <cart_estimatepost>/checkout/cart/estimatePost</cart_estimatepost>
        </secure_url>

**Comment by dbrent-amazon** [comment]
To add to this, in its current state, coupon code and tax calculations are redirecting the buyer from the cart page due to them not using https. This may also cause higher abandon rate.
