### ISSUE TITLE
Send an email to the customer on hard decline

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-plugin#190]
Hi,

when using the async auth we need to inform customers, if we receive a hard decline.
Currently we only send mails, in case of a soft decline.

Edit: Looking at the code it seems we send the same mail for all declines. We should distinguish between hard and soft declines here.

Best wishes
Daniel

**Comment by jonahellison** [comment]
Hi--how should the plugin distinguish between hard and soft declines? And should a new email template be created?

**Comment by danielneu** [comment]
Hi,

yes we need a second template. 
The current one should only be send out if we see a reason code of "InvalidPaymentMethod".
In all other cases (with async auth) the new template should be send out.

I'll mail you templates we use.

~Daniel

**Comment by islandskater43** [comment]
Can you guys loop me in on any action for this? As far as I know, the PWA product does not differentiate between hard and soft decline.

**Comment by ngrices** [comment]
@jonahellison did you receive the templates? If not, I am punting on this until the next milestone.

**Comment by dzlerner** [comment]
The messaging for the soft decline email indicates it is possible for a customer to re-enter their order payment information and "try again", so to speak.

Unless we're missing something, there does not appear to be a way for the customer to edit their payment information from within the Magento Account Interface (nor from the admin).

What is the desired behavior for a customer in this scenario?

**Comment by ngrices** [comment]
@dzlerner The messaging to retry invites the buyer to login to payments.amazon.com and change the payment method associated with the order, which will move the order from Suspended to Open. The asynchronous cron update in Magento will check for Open orders are re-authorize against the new payment method automatically.

**Comment by dzlerner** [comment]
Odd, in the body of the email the link is to the Magento order view.

**Comment by ngrices** [comment]
@jonahellison Can you comment on your commits? Given that 'soft' in this context really means 'retry after you change the payment method', what does inviting the user back to the order view accomplish in this case?

**Comment by jonahellison** [comment]
For soft declines, the wallet widget will appear on the order details page (#158), so the customer is able to select a different payment method within the Magento store.
