### ISSUE TITLE
Mage::getEdition won't work with versions prior to 1.7.x

### ISSUE THREAD

**Issue by barbanet** [amzn/amazon-payments-magento-plugin#194]
The Diagnostis Controller use the method Mage::getEdition().

https://github.com/amzn/amazon-payments-magento-plugin/blob/master/app/code/community/Amazon/Diagnostics/controllers/Adminhtml/DiagnosticsController.php#L47

This method wasn't availabe until Magento 1.7 so the module can't be used with prior versiones.

**Comment by dbrent-amazon** [comment]
Can someone confirm if support for 1.6 is being dropped? I've heard rumors.

**Comment by dbrent-amazon** [comment]
This has been [fixed](https://github.com/amzn/amazon-payments-magento-plugin/commit/a9f67c1076ba562462cd28db12390f54ebf8258a).
