### ISSUE TITLE
Adding a "Pay with Amazon" button to the sidebar cart

### ISSUE THREAD

**Issue by jfain189** [amzn/amazon-payments-magento-plugin#195]
I have a magento website with a sidebar cart equipped with our checkout and paypal checkout buttons. I would like to add a "Pay with Amazon" button to our sidebar cart as well but there doesn't seem to be anyway to achieve this. I asked Amazon Payments support and they told me to forward the question here. Website URL for reference: http://www.precisiontools.com .See below from an amazon support chat:

The only options currently are:

1. As a payment option in the checkout workflow pipeline
2. On the cart page, at the top and bottom
3. On the product page

If you need it anywhere else then you would indeed need to modify the .phtml files which is not something this team handles. I would recommend creating an issue as a feature request on the GitHub site.

**Comment by ngrices** [comment]
Hi 
Please see this article from the wiki 
https://github.com/amzn/amazon-payments-magento-plugin/wiki/Community-and-FAQ#q-id-like-to-place-the-login-with-amazon-or-pay-with-amazon-buttons-elsewhere-on-my-site-such-as-on-a-product-detail-page

and let us know if this resolves your issue.

**Comment by rjamison** [comment]
A quick note that if your sidebar cart is hosted on non-SSL pages, you'll want to change the Pop-Up setting under Login with Amazon to "No".  

The setting can be found in the Magento admin, go to "Configuration" -> "Login with Amazon".  You'll also need to configure a redirect URL shown as a tooltip on the Magento admin page.

<img width="674" alt="screen shot 2015-08-03 at 2 49 53 pm" src="https://cloud.githubusercontent.com/assets/7671574/9048566/f794a50a-39ee-11e5-9b8a-0ecdbbc850f2.png">

You'll set that up inside https://sellercentral.amazon.com.  After logging in, select "Login with Amazon" from the drop-down at the top of the page and enter the URL under "Allowed Redirect URLs".

**Comment by dbrent-amazon** [comment]
@ngrices I am working with @jfain189 on this. When using the method mentioned in the FAQ the site throws all sorts of console errors. The console errors only appear when modifying the XML to add the button. Also whenever they add a product to the cart for the first time the amazon payments button doesn't show. They have to refresh to see it.

![console](https://cloud.githubusercontent.com/assets/9828472/9093348/7e1bc988-3b60-11e5-9df9-2e36513d8d20.png)

**Comment by jfain189** [comment]
Hi, can you guys switch this conversation to
jeremy.fain@infinitemediacorp.com . This is my personal email that is my
work email.

**Comment by ngrices** [comment]
@jfain189 your github account is tied to your email. You need to change it in your account. I dont think this is a generic issue with the extension but rather a customization what is experiencing some issues.

If the goal is to add it to the minicart (the cart shown when clicking the cart link from a product page)
like this.
![screen shot 2015-08-05 at 12 12 28 pm](https://cloud.githubusercontent.com/assets/7907929/9095292/55701790-3b6b-11e5-8247-04ee867271c6.png)

has been fixed in the master branch.
https://github.com/amzn/amazon-payments-magento-plugin/commit/c3dc65010e2cc33df63f872157fe17ddec5f7dc7

In either case, I am closing this issue and @dbrent-amazon @jfain189 can pick this up in a support thread

**Comment by jfain189** [comment]
Ok, that wasnt the goal though. The goal was to add it to our sidebar cart.
See attached. The button shows up on the pages fine but our cart page has
several javascript errors.
