### ISSUE TITLE
"Order Review" step is not loading for the "Magento Core OnePage Checkout" checkout type

### ISSUE THREAD

**Issue by k-filippov** [amzn/amazon-payments-magento-plugin#196]
Amazon_Payments 1.3.0 (there are some diffs with the latest module codebase but they do not influence checkout controller as I see them)
Magento EE 1.11.1.0
Enterprise/Default theme
Checkout Page Type: Magento Core OnePage Checkout

Checkout initiated by clicking on the "Pay with Amazon" button

I'm on the third checkout step of four - "Shipping Method".
Clicking on "Continue" button shows "Loading next step" popup, and then nothing happens when popup disappears.

![shipping-method-amazon-checkout-step](https://cloud.githubusercontent.com/assets/8516585/9121388/b07ae6e0-3c8a-11e5-89d3-93000a419f3b.png)

The screenshot attached shows that it tries to load "payment" checkout section instead of (expected) "review".
My debugging also shows shipping method save is processed by the native Magento controller:
Mage_Checkout_OnepageController::saveShippingMethodAction()

Please check if this is reproducible on your side.

**Comment by ngrices** [comment]
@k-filippov we cannot reproduce this error, are you still seeing this?
