### ISSUE TITLE
Amazon buyer clicking cancel on consent form is sent to blank page

### ISSUE THREAD

**Issue by ngrices** [amzn/amazon-payments-magento-plugin#199]
Repro:

1) Login with Amazon
2) After user/pass click 'Cancel' to not consent to sharing information with merchant

Result:
Buyer is sent to <base url>/amazon_payments/onepage/?error_description=Access%20not%20permitted.&error=access_denied

Which results in a blank page in the browser

**Comment by Anshu-Mishra** [comment]
Any update on this we are facing this issue from quite a long time now.

**Comment by ngrices** [comment]
The click through rate on buyers sharing their customer information versus clicking 'Cancel' is measured at over 99%. As a result the priority for this fix is lower at the moment for some other issues affecting merchant and buyer experience. I do expect it in the 1.3.2 release

**Comment by jonahellison** [comment]
Fixed to redirect to cart if user cancels on Amazon Login consent form (1.4 branch).
