### ISSUE TITLE
Need to about the Google Analytic Tracking with Pay with Amazon extension

### ISSUE THREAD

**Issue by niteshlakhwani** [amzn/amazon-payments-magento-plugin#202]
Hi,

We are using a older Amazon checkout extension on the our website (www.havahart.com) but there is a problem in that extension as it do not track the sale with Google Analytics when they come to Amazon checkout for finalizing the purchase. We are losing visibility to these orders.

And on raising the ticket with Amazon Support (Case ID1449395001), they responded that to use the new extension "Pay with Amazon" (
http://www.magentocommerce.com/magento-connect/pay-with-amazon-for-magento.html)

I have the following questions about the extension:

    Is the extension compatible with Magento EE 1.14.X?
    Is this extension compatible to Multi-website and Multistore architecture of Magento?
    Is this extension compatible to Responsive theme of EE 1.14
    Do this extension support to track the sale conversion in GA, below is the details about the issue which we are facing in the older extension would like to know if this new extension will overcome?
        This issue is related to tracking data in Google Analytics.  When a user chooses to pay with Amazon Payments, all of the session data associated with that user is split from the order data.  So, what happens is that one user's actions turn into two separate sessions in analytics.  One session is exclusively acquisition and browsing data while one session is exclusively order/ecommerce data and there is no way for us to link these two sessions.

        When paying through Paypal or our regular cart, this data does not split and is viewed as one session.
        For example:
        Scenario 1 -- User comes to site via Google CPC ad.  User pays using our regular cart.  Data shows up in analytics as revenue attributed to CPC.

        Scenario 2 -- User comes to site via Google CPC ad.  User pays using Amazon Payments.  Data shows up in analytics as a user who came via CPC and did not buy anything and as a user who came to the site directly, did nothing, and somehow purchased something.
 ----
        Our wish is that the data remains connected when using Amazon Payments.  Otherwise we have large amounts of revenue that we cannot track/attribute to any specific actions.

Thanks & Regards
Nitesh Lakhwani

**Comment by rjamison** [comment]
Hi Nitesh,

The extension supports EE 1.11+.  It does support Magento's native capability of supporting multiple websites/stores.  It's generally compatible with responsive themes and tested with the default Magento provided responsive theme.  

I see that you're using the older Checkout by Amazon platform on your site, this new integration uses widgets embedded on your website so should allow you to maintain your Google Analytics tracking throughout the checkout process.  You can see the checkout experience with the extension on this website:  https://www.flintandtinderusa.com

Thanks,

Robert.

**Comment by niteshlakhwani** [comment]
Thanks Robert for the Reply and providing the details about the extension's support and confirming about GA compatible feature

**Comment by niteshlakhwani** [comment]
Hi Robert,
Two more questions:
1) Does the extension supports Split Shipment functionality?
2) Provided extension require following credentials to configure amazon payment method in Magento,
•         Seller/Merchant ID
•         MWS Access Key
•         MWS Secret Key
•         Client ID
•         Client Secret
•         Checkout Page Type
In old extension, there was provision to configure following parameters values to send in request to Amazon, but in new extension there is no such fields, can you please guide us to know if the following parameters are needed anymore or are important from Merchant's point of view:
•         Access Key ID (Not sure, But it can be match with Client ID in new extension )
•         Secret Key ID (Not sure, But it can be match with Client Secret in new extension )
•         Merchant Login
•         Merchant Password
•         Merchant Name
•         Merchant Token
•         Standard Rate
•         Expedited Rate
•         OneDay Rate
•         TwoDay Rate

Thanks & Regards
Nitesh Lakhwani

**Comment by ngrices** [comment]
Hi Nitesh

1) Split shipments is not supported at this point. The order can be configured to Authorize and Capture at the time of purchase, or Authorize at the time of purchase and then capture when invoicing the order (shipping)
2) The MWS Access Key/Secret Key map to the Access Key ID and Secret Key ID but the other values are specific to an older payments product at Amazon called Checkout By Amazon. You should click the 'Login to get your keys' button in the Magento admin after installing the extension where you can configure your account and get the other needed keys from the registration flow.

**Comment by islandskater43** [comment]
Closing this item. Reopen or add new issue if there are still any open questions.
