### ISSUE TITLE
Add Support For SoftDescriptor

### ISSUE THREAD

**Issue by dbrent-amazon** [amzn/amazon-payments-magento-plugin#204]
The SoftDescriptor is what appears on billing statements. I have been asked many times how to change this. The SoftDescriptor is set during the "Authorize" API call.

https://payments.amazon.com/documentation/apireference/201751630#201752010

By default it is set to "AMZ*<SELLER_NAME> amzn.com/pmts WA" and can only be 16 characters long. I'm not sure what the verbiage would be as the Pay with Amazon option, however.

**Comment by ngrices** [comment]
Proposed functionality:
Use Store view name as default SoftDescriptor in Authorize call. Document that store name will be truncated at 16 characters and provide instructions for manually changing the SoftDescriptor in the code, which should amount to a single line/string change.

**Comment by ngrices** [comment]
behavior will be new config for Soft Descriptor, with note describing how Store Name will be used if blank

**Comment by jonahellison** [comment]
Added "Soft Descriptor" config field under "Transaction." Field is limited to 16 chars.
Help text: "Billing descriptor to display on credit card statements. Limited to 16 characters. If left blank, current Magento store name will be used."
