### ISSUE TITLE
Only Load Widgets.js on Product Page if Enabled

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-plugin#206]
A merchant was complaining that if the PWA plugin is enabled, but the "Display on Product Page" is set to No, we still include the Widgets.js file on the product detail page. 

Instead, can we perform the same check on the product detail page to see if the button needs to be displayed, and only include the JS in that case?

**Comment by lfolco** [comment]
i would love to have this as well.

**Comment by islandskater43** [comment]
It appears that we also load Widgets.js on the home page. If possible, would be great to remove this, unless the merchant has the button in the mini cart.

**Comment by jonahellison** [comment]
Removed Widgets.js when "Display on Product Page" is set to "No" or minicart is empty
