### ISSUE TITLE
Decline handling / Email not sent for InvalidPaymentMethod with asynchronous authorization

### ISSUE THREAD

**Issue by jsgut** [amzn/amazon-payments-magento-plugin#208]
Hi,

I just installed the latest EU branch that was released a few minutes ago https://github.com/amzn/amazon-payments-magento-plugin/tree/eu 
After simulating an InvalidPAymentMethod decline, the Magento history of the order will display that the transaction was declined and an email was sent to the customer but no email is sent.
Could you please take a look at it?
Thank you.
![email_invalid_payment_method](https://cloud.githubusercontent.com/assets/14095640/9637040/d3c5e4e6-519e-11e5-9ba8-84994b3bb10e.png)

**Comment by ngrices** [comment]
@jonahellison I did merge the change from master in EU prior to him testing.

**Comment by danielneu** [comment]
Hi,

just tested with the most current eu branch.
Things are looking good, sendmail refused to send the mails out, but the plug-in is doing it right.

I am now looking into the server configuration to get this sorted. We can close this one.

Best wishes
Daniel
