### ISSUE TITLE
Add notification for delay for Pay with Amazon button on product page

### ISSUE THREAD

**Issue by samir-khoja** [amzn/amazon-payments-magento-plugin#212]
When a merchant uses redirect instead of popup for their Login with Amazon button. The Pay with Amazon button on the product page has a delay (5 seconds where it looks like nothing is happening) when it is clicked. The button does not have a delay from the cart page, only when it is clicked from a specific product page. The network tab shows that there is activity happening but the page doesn't indicate anything is happening with a loading icon or anything. The activity that is causing the delay is an additional POST and GET that does not happen from the cart page. I believe this additional POST and GET is adding the product to the cart then verifying the cart details.

**Comment by jonahellison** [comment]
Added "disabled" CSS style (opacity @ 50% with "wait" cursor) for "Pay with Amazon" shortcut button on click (1.4 branch).
