### ISSUE TITLE
Center Button in Minicart

### ISSUE THREAD

**Issue by dbrent-amazon** [amzn/amazon-payments-magento-plugin#215]
I was going to just push this but wanted to make sure it didn't break anything beforehand. This small change will center the Pay with Amazon button in the minicart regardless of which size it's set to.

![center](https://cloud.githubusercontent.com/assets/9828472/10206189/7c243ea8-677a-11e5-898f-d07eeabc7caf.png)

<pre>app/design/frontend/base/default/template/amazon_payments/button.phtml</pre>

Change the style in line 13 from:
`<div id="<?php echo $this->getAmazonPayButtonId(); ?>" class="amazon-pay-button" style="float:right;margin-bottom:10px;"></div>`

To:
`<div id="<?php echo $this->getAmazonPayButtonId(); ?>" class="amazon-pay-button" style="display:inline-block;margin:0 auto 10px;"></div>`

I realize it's a minor change but it's aesthetically pleasing.

**Comment by mxsigns** [comment]
Thanks @ngrices
@dbrent-amazon unfortunately this does not center the button for me also any thoughts on correcting the tooltip z-index?
(image on https://github.com/amzn/amazon-payments-magento-plugin/issues/72 )

**Comment by jonahellison** [comment]
Button centering CSS is in place and works for EE. CE and other themes may require modifying the core CSS, since the parent div is floating the buttons to the right.
