### ISSUE TITLE
Wrong redirect URLs being shown

### ISSUE THREAD

**Issue by dbrent-amazon** [amzn/amazon-payments-magento-plugin#216]
In cases where server rewrites are not being used the 'Allowed Redirect URLs' are not valid. Merchants without rewrites will have to white list URLs like so (note the added index.php):

`https://www.example.com/index.php/amazon_payments/checkout/authorize/`

Can we somehow detect if they are using rewrites (I assume for SEO reasons) and display the correct URLs?

**Comment by jonahellison** [comment]
Added detection for mod_rewrite (if not enabled, will add index.php). Also fixed URLs based on current store view scope. (1.4 branch.)
