### ISSUE TITLE
Default Scope cannot be empty / Validation only on default scope

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-plugin#219]
Hi,

when configuring the plugin and leaving the default scope empty, the verification on save will always fail.
The validation only takes the default scope into account, not the scope currently activated.

Therefor it is not possible to leave the default empty, merchants will always see an error when saving.

As the save method does not take any parameters, is there actually a way to determine which scope the save was issued from? If not, I'm voting for a dedicated button to do the verification per scope.

Best wishes
Daniel

**Comment by ngrices** [comment]
@jonahellison I want to remove the automated key checking altogether. This has caused too many problems and does not fit into the upcoming SimplePath release

Remove functionality in afterSaveCommit here https://github.com/amzn/amazon-payments-magento-plugin/blob/f66bdd2fc0c21fa2fb5bc02f09f7df06fa6d4291/app/code/community/Amazon/Payments/Model/System/Config/Backend/Enabled.php

**Comment by jonahellison** [comment]
Removed _afterSaveCommit key validation (1.4 branch).
