### ISSUE TITLE
cURL using IPv6

### ISSUE THREAD

**Issue by dbrent-amazon** [amzn/amazon-payments-magento-plugin#220]
In some cases (exactly 2 that I have encountered so far) cURL will try to resolve using IPv6 which results in an exception stating that it cannot resolve "mws.amazonservices.com".

The fix was to add the following cURL option to lib/OffAmazonPaymentsService/Client.php.

`curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);`

I did not want to submit a pull request since I am not sure if this will break (or be ignored) PHP prior to 5.3.

**Comment by ngrices** [comment]
Might be a doc bug in that we want to just call it out, but can you take a look @jonahellison

**Comment by jonahellison** [comment]
Resolved in 1.4 branch.
