### ISSUE TITLE
Emails not listed at transaction E-Mails in Magento

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-plugin#221]
Hi,

the E-Mail templates for declines are not added to the transactional E-Mails.
This is the place ,merchants will search for it, if they want to add some styling.

The lookup of mails should be against the transactional mails.

Best wishes
Daniel

**Comment by gbear** [comment]
@danielneu custom transactional emails are in place for Async templates, all other templates (new orders, invoices, shipping, etc...) are using the usual Magento templates and can be overridden as necessary. For example, there are not specific "new order" emails specific to Amazon Payments orders, the new order emails set generally for the store are used.

To customize these, you go in the admin to System > Transactional Emails, and click on Add New Template.
![image](https://cloud.githubusercontent.com/assets/11601/14093955/c47887da-f506-11e5-8f80-a7892d85ef0a.png)

You then select the template you want to override, that will load the default and you can customize the copy/html and insert variables.  
![screen shot 2016-03-28 at 4 59 46 pm](https://cloud.githubusercontent.com/assets/11601/14094032/85eddaaa-f507-11e5-888e-c4943735fda3.png)

**Comment by danielneu** [comment]
Thanks @gbear ,

@ngrices would this make sense as a short section in the guide?
