### ISSUE TITLE
Pay with Amazon button triggers Adobe Flash plugin

### ISSUE THREAD

**Issue by cdietzols** [amzn/amazon-payments-magento-plugin#222]
Our checkout process has been requiring Adobe Flash, which triggers a browser warning if a customer's Flash plugin is out-of-date. After further investigation, I found that the code associated with the "Pay with Amazon" button is triggering the plugin.

Here's an example on one of our sites: http://www.united-states-flag.com/checkout/cart/
To demonstrate this button as the cause, paste the code below in an empty .html file and replace the [SELLER_ID] with your own. This code was generated by the Magento Amazon Payments plugin:

```
<div id="AmazonPayButtonTop"></div>
<script src="https://static-na.payments-amazon.com/OffAmazonPayments/us/sandbox/js/Widgets.js?sellerId=[SELLER_ID]"></script>
<script type="text/javascript">
    var authRequest;

    var AmazonButtonOptions = {
        type: "PwA",
        color: "Gold",
        size: "medium",
        authorization: function () {
            loginOptions = {
                scope: "profile payments:widget payments:shipping_address",
                response_type: 'token',
                popup: 0
            };

            authRequest = amazon.Login.authorize(loginOptions, "http://www.example.com");
        },
        onError: function (error) {
            console.log(error);
        }
    };

    OffAmazonPayments.Button("AmazonPayButtonTop", "[SELLER_ID]", AmazonButtonOptions);
</script>
```

If you open up this code in FireFox, you should see the plugin icon appear next to the url. Or, if your Flash player is out-of-date, you'll see a warning.

Is it possible to generate the Pay with Amazon button without using the Flash plugin so that flash does not appear during our checkout process?

**Comment by dbrent-amazon** [comment]
Where is the plugin icon you are referring to? I don't see it on your site or on my test site. The plug-in does not use Flash.

**Comment by ngrices** [comment]
I am non-repro with the above code sample. The image renders as expected.
<img width="391" alt="screen shot 2015-11-10 at 4 09 03 pm" src="https://cloud.githubusercontent.com/assets/7907929/11080053/831a41d8-87c5-11e5-839a-8ba2fcd437aa.png">

**Comment by ngrices** [comment]
in Firefox. 
<img width="378" alt="screen shot 2015-11-10 at 4 11 25 pm" src="https://cloud.githubusercontent.com/assets/7907929/11080079/c0c45014-87c5-11e5-9d36-36eeabcf8ad3.png">

@cdietzols is there some toolbar or other firefox plugin causing this in your browser? can you try a different browser?

**Comment by cdietzols** [comment]
@dbrent-amazon  @ngrices  thank you both for the quick replies.

To be more specific, there's an icon that appears next to the globe when running a page with flash:
![flashmessage2](https://cloud.githubusercontent.com/assets/8460300/11094903/6fe147f6-8860-11e5-8812-90349cf2fbd3.PNG)

Further, if someone is running an out-of-date version, the icon becomes red and a message is displayed:
![flash](https://cloud.githubusercontent.com/assets/8460300/11094947/a6525000-8860-11e5-8a84-9438a7e1c310.PNG)

The button rendering and functionality works fine in all cases. If flash is disabled, it continues to work fine. Our concern is regarding the flash messages--we would not want a customer to become distracted or turn away from checkout because of the warning messages.

In the code, the line with "OffAmazonPayments.Button()" triggers the plugin. If I comment that line only, the icon disappears.

We ran some further tests this morning, and it looks like we were only able to get the plugin icon to show in FireFox on a Windows machine. IE, Chrome, and Safari don't seem to offer any indications as to whether a page has required the flash plugin, and FireFox on Mac does not show any plugin icon. Also, if any of these browsers lack a flash plugin, then no warnings or icons are shown.

**Comment by danielneu** [comment]
Thanks for reporting.

This is not related to the Magento plugin and no fix is possible in this project.
This needs to be addressed at a higher level and will then be effective for this solution automatically.

Resolving as not fixable within this plugin.
