### ISSUE TITLE
Magento EE feature "Gift wrapping" not supported

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-plugin#223]
This feature is not yet supported and should be added.
I do have more information, if needed, reach out pls.

Best wishes
Daniel

**Comment by danielneu** [comment]
There is a pull request on the eu branch to add the support, please review: #227

**Comment by ngrices** [comment]
@jonahellison to review and merge all outstanding pull requests

**Comment by jonahellison** [comment]
Added CE/EE Gift Message and EE Gift Wrapping support.
