### ISSUE TITLE
Upgrade to magento 2.0

### ISSUE THREAD

**Issue by eclipse3211** [amzn/amazon-payments-magento-plugin#225]
any way you can upgrade this extension make it available for magento 2.0?

**Comment by ngrices** [comment]
Hi @eclipse3211 
We are planning to release a separate Magento 2 extension in the next few months. Stay tuned!

**Comment by robotarmies** [comment]
@ngrices saw this was closed yesterday, but are you still planning on testing/releasing the M2 version in the near future? Thanks!

**Comment by ngrices** [comment]
hi @robotarmies see my above comment. We will have a magento 2 extension available to the public in Q2 this year
