### ISSUE TITLE
Turpentine/Varnish + Amazon Payments not working

### ISSUE THREAD

**Issue by miguelbalparda** [amzn/amazon-payments-magento-plugin#226]
Hello guys, any chance we can work together on this issue? https://github.com/nexcess/magento-turpentine/issues/1054

**Comment by dbrent-amazon** [comment]
I commented on that issue. If disabling Login with Amazon fixes the problem then it will require further research elsewhere.

**Comment by dbrent-amazon** [comment]
Seems disabling Login with Amazon fixed the issue. The issue is with the Pay with Amazon plug-in itself, not this project. You should be able to close the issue.

**Comment by miguelbalparda** [comment]
Fixed, thank you guys!
