### ISSUE TITLE
Amazon Payments ignoring the shipment rules and restrictions (using productMatrix Shipping Extension)

### ISSUE THREAD

**Issue by nehaa34** [amzn/amazon-payments-magento-plugin#230]
We have a report that Amazon Payments is ignoring the shipment rules and restrictions setup in Magento via a shipping extension. The shipping extension can be found here: http://webshopapps.com/us/productmatrix-shipping-extension.html

Due to this issue customer are able to order to any destination overriding the shipment rules and logic.  Is there a resolution for this issue?

**Comment by golferejoe16** [comment]
I created this ticket with the amazon support folks, to bandaid the problem I've added a check to see if shippingMethod exists in the setReview function. If shippingMethod doesn't exist I call"
            this.toggleOrderSubmit(true);
and then hide the loader spinner just to be a bit more aesthetically pleasing.\:
            var loader = $("amz-review-loader");
            loader.hide();

**Comment by ngrices** [comment]
@jonahellison can you see if this logic could be generically applied? If not, we can document in FAQ
