### ISSUE TITLE
Compatability with SUPEE-6788

### ISSUE THREAD

**Issue by ddsgadget** [amzn/amazon-payments-magento-plugin#231]
Is this extension compatible with the SUPEE-6788 patch from Magento? (https://magento.com/security/patches/supee-6788) . I didn't see any code updates since that patch was released, so it's not clear, whether this has been addressed yet. thanks.

**Comment by danielneu** [comment]
Yes, this plug-in has not been affected by this patch.

Best wishes
Daniel

**Comment by ngrices** [comment]
Please re-open the issue if you can confirm any issues. As @danielneu said, there have been no issues so far
