### ISSUE TITLE
Login: Email Confirmation Required Bug

### ISSUE THREAD

**Issue by THEANONYMOU5** [amzn/amazon-payments-magento-plugin#233]
In the Magento admin if the customer settings are set so that a customer confirmation email is required for a user to login to their account it creates an issue.  When attempting to login in with 'Login with Amazon' the account is created and is ready to use but the user is not notified that they must confirm their email. I feel this is a bug and wanted to bring it up.

My goal for the user experience is slightly different though.  
 In my implementation I will be overriding the 'loginWithToken()' function located in Amazon/Login/Model/Customer.php.  Immediately after the '$this->createCustomer()' I will be checking the confirmation for the customer and setting it to confirmed. This is because we don't not need the customer to confirm if they are coming from an amazon account.

**Comment by THEANONYMOU5** [comment]
My Fix:
File: Amazon/Login/Model/Customer.php
Function: loginWithToken(...)
`// Create account
                if (!$this->getId()) {
                    $this->createCustomer($amazonProfile);
                    

//ADDED BY: THEANONYMOU5  - fix login issue when confirmation email is required
                    if ($this->getConfirmation()) {
                        try {
                            $this->setConfirmation(null);
                            $this->save();
                        } catch (Exception $e) {
                            Mage::logException($e);
                        }
                    }
//END ADDED CODE
                }`

**Comment by jonahellison** [comment]
Added confirmation check during customer creation (1.4 branch).
