### ISSUE TITLE
Encrypt amazon api values in admin

### ISSUE THREAD

**Issue by jperalta1989** [amzn/amazon-payments-magento-plugin#234]
Our company needs the option to encrypt these values so that only the one person that knows them is the one that can set up the module. This includes the values on the database. I had sent you a pull request on January 6th that is basically forcing this to happen. We would prefer for you to have this as an option in your next module so that we can continue to upgrade this module.

Thank you

**Comment by ngrices** [comment]
We will include the pull request in the 1.4 release once our developers have confirmed the functionality
