### ISSUE TITLE
1st checkout step button does not obey the login experience config

### ISSUE THREAD

**Issue by danielneu** [amzn/amazon-payments-magento-plugin#236]
Hi,

this button:
https://github.com/amzn/amazon-payments-magento-plugin/blob/f66bdd2fc0c21fa2fb5bc02f09f7df06fa6d4291/app/design/frontend/base/default/template/amazon_payments/button.phtml

does not check for popup/redirect and uses the payment color/size configuration.

Please check

**Comment by danielneu** [comment]
My bad, wrong file in the initial issue:
https://github.com/amzn/amazon-payments-magento-plugin/blob/f66bdd2fc0c21fa2fb5bc02f09f7df06fa6d4291/app/design/frontend/base/default/template/amazon_payments/onepage/button.phtml

**Comment by islandskater43** [comment]
This is already fixed. Just forgot to close the issue.

**Comment by islandskater43** [comment]
Here's the commit: https://github.com/amzn/amazon-payments-magento-plugin/commit/812ed4f6eedc5676458504058cda180bec82cfce
