### ISSUE TITLE
Slows down 'add to cart' on Magento

### ISSUE THREAD

**Issue by ospinc** [amzn/amazon-payments-magento-plugin#237]
Amazon Payments has slowed down the "add to cart" function across our entire site.  We disabled it to confirm where the delay was coming from and it was Amazon Payments.

**Comment by ngrice** [comment]
Hi there

Thanks for logging the issue. Would it be possible to capture the network calls the browser is making using the developer tools in chrome and share in this ticket so we can see which calls are causing the delay?

**Comment by ospinc** [comment]
Yes.

**Comment by ngrices** [comment]
Closing for now. Please re-open if you have the supporting network calls data
