### ISSUE TITLE
Inadvertently calling indexAction on redirect during error condition

### ISSUE THREAD

**Issue by ngrices** [amzn/amazon-payments-magento-plugin#241]
Recently an issue has come up regarding a few URLs which produce blank responses with a 200 OK response code.  One URL we've found producing this issue is from the Amazon Payments module.  The URL is:

https://www.DOMAIN.com/amazon_payments/onepage/?error_description=Access%20not%20permitted.&error=access_denied

Unfortunately, I don't have any detail on what actions precisely triggered this URL, but this is a blank page due to an empty controller action:

https://github.com/amzn/amazon-payments-magento-plugin/blob/master/app/code/community/Amazon/Payments/controllers/OnepageController.php#L20

Perhaps the intention of this action was to forward to the checkout/onepage/index route in an error scenario?

It looks like this is happening when this code fails to authorize the token, for whatever reason:

https://github.com/amzn/amazon-payments-magento-plugin/blob/master/app/code/community/Amazon/Payments/Controller/Checkout.php#L40

Since the code doesn't end up redirecting the user, it ends up handling the blank route, which returns no response.

I'd recommend calling this if the response is handled in preDispatch:

$this->setFlag('', Mage_Core_Controller_Varien_Action::FLAG_NO_DISPATCH, true);

And then inside the index action, somehow handle the error condition or bad request.  This way, it won't call the indexAction method when the redirect occurs.

We do see these errors occur from time to time in our logs.  Unfortunately, we're not sure exactly the cause, so we don't know the current experience users get exactly.

**Comment by ngrices** [comment]
More information from reporting merchant

The user is redirected to that URL whenever they cancel during the checkout flow. if you attempt an Amazon checkout, log in, then click cancel rather than completing your purchase.

**Comment by jonahellison** [comment]
Fixed redirect to prevent blank response (1.4).
