### ISSUE TITLE
'The Value 'CAD' is invalid for the Parameter 'currencyCode''

### ISSUE THREAD

**Issue by cralls** [amzn/amazon-payments-magento-plugin#242]
Does this extension support canadian dollars?

exception 'OffAmazonPaymentsService_Exception' with message 'The Value 'CAD' is invalid for the Parameter 'currencyCode'' in /var/www/html/spectrum-supplements.ca1.9.2/lib/OffAmazonPaymentsService/Client.php:914 Stack trace: #0 /var/www/html/spectrum-supplements.ca1.9.2/lib/OffAmazonPaymentsService/Client.php(862): OffAmazonPaymentsService_Client->_reportAnyErrors('_invoke(Array) #2 /var/www/html/spectrum-supplements.ca1.9.2/app/code/community/Amazon/Payments/Model/Api.php(98): OffAmazonPaymentsService_Client->setOrderReferenceDetails(Object(OffAmazonPaymentsService_Model_SetOrderReferenceDetailsRequest)) #3 /var/www/html/spectrum-supplements.ca1.9.2/app/code/community/Amazon/Payments/Model/Api.php(302): Amazon_Payments_Model_Api->request('setOrderReferen...', Array) #4 /var/www/html/spectrum-supplements.ca1.9.2/app/code/community/Amazon/Payments/Model/PaymentMethod.php(237): Amazon_Payments_Model_Api->setOrderReferenceDetails('P01-5023624-054...', 525, 'CAD', '300000130', 'CA View') #5 /var/www/html/spectrum-supplements.ca1.9.2/app/code/community/Amazon/Payments/Model/PaymentMethod.php(84): Amazon_Payments_Model_PaymentMethod->order(Object(Mage_Sales_Model_Order_Payment), 525) #6 /var/www/html/spectrum-supplements.ca1.9.2/app/code/core/Mage/Sales/Model/Order/Payment.php(334): Amazon_Payments_Model_PaymentMethod->initialize('authorize_captu...', Object(Varien_Object)) #7 /var/www/html/spectrum-supplements.ca1.9.2/app/code/core/Mage/Sales/Model/Order.php(898): Mage_Sales_Model_Order_Payment->place() #8 /var/www/html/spectrum-supplements.ca1.9.2/app/code/core/Mage/Sales/Model/Order.php(1116): Mage_Sales_Model_Order->_placePayment() #9 [internal function]: Mage_Sales_Model_Order->place() #10 /var/www/html/spectrum-supplements.ca1.9.2/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array) #11 /var/www/html/spectrum-supplements.ca1.9.2/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks() #12 /var/www/html/spectrum-supplements.ca1.9.2/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save() #13 /var/www/html/spectrum-supplements.ca1.9.2/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder() #14 /var/www/html/spectrum-supplements.ca1.9.2/app/code/core/Mage/Checkout/Model/Type/Onepage.php(812): Mage_Sales_Model_Service_Quote->submitAll() #15 /var/www/html/spectrum-supplements.ca1.9.2/app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder() #16 /var/www/html/spectrum-supplements.ca1.9.2/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction() #17 /var/www/html/spectrum-supplements.ca1.9.2/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder') #18 /var/www/html/spectrum-supplements.ca1.9.2/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http)) #19 /var/www/html/spectrum-supplements.ca1.9.2/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch() #20 /var/www/html/spectrum-supplements.ca1.9.2/app/Mage.php(684): Mage_Core_Model_App->run(Array) #21 /var/www/html/spectrum-supplements.ca1.9.2/index.php(83): Mage::run('', 'store') #22 {main}

**Comment by danielneu** [comment]
Hi,

thanks for the request.
Unfortunately it is at the moment not possible to transact in this currency.

Best wishes
Daniel

**Comment by cralls** [comment]
Hi Daniel,

Is this something that was taken out of the latest Amazon extension? Because it was working fine until we upgraded.

**Comment by ngrices** [comment]
@cralls Merchant accounts for Amazon Payments are only supported for the US and EU and UK. The key difference being the currency on which the transactions are made (USD, EUR, GBP).

It is possible in a Magento store to display items in CAD on your shop, have the backend convert the CAD price to the configured currency and then call the Amazon API in the converted currency.
