### ISSUE TITLE
Widget Optimization on Standalone checkout

### ISSUE THREAD

**Issue by ngrices** [amzn/amazon-payments-magento-plugin#244]
Load the Shipping Method and Order Summary (review) blocks in the same Ajax request, which is fired from the Address Widget's onAddressSelect callback function. This should improve total backend time and make the frontend appear smoother. (The checkout page extends Mage's OnePage checkout, which has a separate Ajax call for each section, but the block rendering can be combined.)

**Comment by jonahellison** [comment]
Replaced shippingMethod ajax call with addressSelect ajax call, which combines rendering of shipping method and review blocks.
