### ISSUE TITLE
IWD with amazon payments

### ISSUE THREAD

**Issue by advanceduzer** [amzn/amazon-payments-magento-plugin#248]
I'm using IWD one step checkout (free version)
On the amazon payment when i click on place order i'm getting in console:
 review.save is not a function

**Comment by ngrices** [comment]
@jonahellison can we squeeze this one into the 1.4.1 milestone?

**Comment by jonahellison** [comment]
@advanceduzer do you know if your theme has customized the "Place Order" button?

The "Place Order" button needs to contain this class: `class="button btn-checkout"`

The template file is: checkout/onepage/review/button.phtml

Thanks

**Comment by advanceduzer** [comment]
Thank you!
It helps
There was different class
