### ISSUE TITLE
PwA button on mini cart leads to out of box redirect whitelist error

### ISSUE THREAD

**Issue by gideonsergei** [amzn/amazon-payments-magento-plugin#256]
Default SimplePath config (Magento 1 page checkout, show on cart = yes, show on product view = no, display as payment option = no, popup = yes) has button on mini cart but if no URLs whitelisted will fail with whitelisting error on popup. 

Should write the whitelist return URL regardless of whether merchant has popup = yes or no

**Comment by islandskater43** [comment]
Removed default placement in minicart in issue #284 and added config option.
