### ISSUE TITLE
Other marketplaces than US

### ISSUE THREAD

**Issue by JanWGK** [amzn/amazon-payments-magento-plugin#257]
Hello, is it possible to make this module available for european marketplaces? I tried it, but it seems not to work with a german Amazon account...

**Comment by danielneu** [comment]
Hi,

there is a different module for EUrope available on Magento connect:
https://www.magentocommerce.com/magento-connect/login-and-pay-with-amazon-advanced-payment-apis-for-europe.html

Best wishes
Daniel

**Comment by JanWGK** [comment]
Hi Daniel, 
thanks for the link. We have used this module before, but it is not compatible with Firecheckout...
Anyway, I found that there is an eu branch available in this repository and got it already working. 
Do you know, if this branch will be further devoloped?

Best regards,
Jan

**Comment by danielneu** [comment]
Hi Jan,

I am not sure if the eu branch is up-to-date with the master.
Is there a way I can directly contact you to discuss this in detail?

Best wishes
Daniel

**Comment by danielneu** [comment]
Discussing options offline.
