### ISSUE TITLE
Backend not loading after module installation

### ISSUE THREAD

**Issue by aliimirza** [amzn/amazon-payments-magento-plugin#260]
Hi,

Just copied all the files to appropriate directories but got the following error when reloaded backend.

Fatal error: Call to undefined function apache_get_modules() in MagentoHome/app/code/community/Amazon/Payments/Model/System/Config/Backend/Popupcomment.php on line 22

**Comment by jonahellison** [comment]
Hello--a fix is committed now that will detect whether the Apache PHP extension is installed.

**Comment by aliimirza** [comment]
Thanks, problem solved.
