### ISSUE TITLE
Script Loading Issue

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-plugin#261]
After #161 was fixed, we've seen a couple issues with jQuery. Need to further investigate proper JS loading and whether the jQuery no conflict call is doing what we expect.

**Comment by islandskater43** [comment]
FYI @amznmode

**Comment by snoroozi** [comment]
Same Here

**Comment by islandskater43** [comment]
Hey @snoroozi - can you try and remove the jQuery.noConflict() line in the following locations and see if that resolves your issue?

https://github.com/amzn/amazon-payments-magento-plugin/blob/master/app/design/frontend/base/default/template/amazon_payments/script.phtml#L35

https://github.com/amzn/amazon-payments-magento-plugin/blob/master/app/design/frontend/base/default/template/amazon_payments/login/script.phtml#L101

**Comment by snoroozi** [comment]
It doesn't help

**Comment by snoroozi** [comment]
Any further updates to this?  In fact commenting those out causes a few new issues.

**Comment by islandskater43** [comment]
@snoroozi is this the same as issue #284 ?

**Comment by snoroozi** [comment]
Not exactly, but probably yes

**Comment by gbear** [comment]
Remove from minicart for default installation, should cross-solve #284

**Comment by jonahellison** [comment]
Removed payment button from minicart. Added config option to toggle display ("Show in Minicart").
