### ISSUE TITLE
IWD Inline Amazon Integration?

### ISSUE THREAD

**Issue by octoxan** [amzn/amazon-payments-magento-plugin#262]
I notice the FAQs say that this extension works with IWD's opc module. Once in the IWD checkout page the Pay With Amazon button does appear, but clicking it appears to do nothing but refresh the page.

Under Payment Methods > Login and Pay with Amazon I noticed there is a dropdown form "Checkout Page Type" with the options "Magento Core OnePage Checkout", "Amazon Standalone Checkout" and "Amazon Standalone Checkout in Modal Window". Is there no way to inline the Amazon payment integration with IWD's opc? 

In the default checkout method after you login with Amazon it shows you payment/shipping options from your Amazon account right in the page.

**Comment by islandskater43** [comment]
The supported functionality for IWD opc is to simply load the button and when clicked, redirect the user back to the Amazon Standalone Checkout. The FAQ should call this out, and mention that the config needs to be set that way. 

At present, we have not extended IWD's opc to support an inline version of the Amazon Payments checkout like we have for Magento's native OnePage checkout.

**Comment by octoxan** [comment]
Ah good to know. Yeah I think the FAQs should definitely mention this somewhere. Was trying to figure out why IWD was broken for me.

**Comment by islandskater43** [comment]
Documented here: https://github.com/amzn/amazon-payments-magento-plugin/wiki/Community-and-FAQ#q-i-see-that-the-112-release-of-the-extension-works-with-the-firecheckout-and-iwd-onepage-checkout-extension-how-do-i-enable-that
