### ISSUE TITLE
Limiting Shipping to other Countries

### ISSUE THREAD

**Issue by schroffd** [amzn/amazon-payments-magento-plugin#263]
Using Magento (Enterprise Edition) 1.14.2.0 and the Amazon Payments module v 1.3.0. Wanting to stop shipping to Canada, though we can still accept Canada billing addresses. In the Magento control panel, at System->Configuration->General->Countries Options->Allow Countries set so that Canada is not a valid country; however, it is still receiving Canada orders through Amazon Payments.

**Comment by islandskater43** [comment]
Should be able to pull this value via something like the following:

    $allowCountries = explode(',', (string)Mage::getStoreConfig('general/country/allow', $store));

And then check that the country for the address returned from the GetOrderReferenceDetails API call is in the `$allowCountries` string.
