### ISSUE TITLE
Email and customer information not store in sales_flat_order table

### ISSUE THREAD

**Issue by ashokdubariya** [amzn/amazon-payments-magento-plugin#265]
Hello,
We have installed and configured Amazon Payment Magento Extension in many projects and it's working fine on all project.

But recently we have installed in one projects (Magento ver. 1.8.0.0) and we are getting one issue on Admin >> Sales >> Order >> View page. We are unable to see customer's email address. Please check attached for more information.

We have checked in details with database and didn't found customer information in sales_flat_order table.

Can you please let me know why email and customer information not storing into sales_flat_order table with Amazon Payment method for (Magento ver 1.8.0.0)?

Also let us know what is the solution for that?

Thanks
Ashok Dubariya
![amazon-payments](https://cloud.githubusercontent.com/assets/12961793/15347842/b6ccc66a-1ce2-11e6-9999-50667835d318.png)

**Comment by islandskater43** [comment]
Hi Ashok - Can you confirm which version of the plugin you are using, and from where you installed it?

**Comment by ashokdubariya** [comment]
Hello Matt,

Thanks for your reply.

I have downloaded extension from here: https://github.com/amzn/amazon-payments-magento-plugin
And this is working fine on all projects just getting above issue in one project which is developed in Magento ver. 1.8.0.0

Also i have checked version of this extension is 1.3.0.

**Comment by ashokdubariya** [comment]
Hello Matt,
Just for your information, I resolved this issue. Just copied layout and template files from base to our theme directory.
This is miracle for me because this extension is working fine with base directory also for other projects.

Thanks
Ashok Dubariya
