### ISSUE TITLE
Error at checkout - asked to enter address, first name and last name

### ISSUE THREAD

**Issue by cryogenn** [amzn/amazon-payments-magento-plugin#266]
Hi - I'm not sure exactly what is required, so please let me know.

I am on Magento community v 1.9.2.4 and I installed the Amazon plugin originally using Magento Connect but then upgraded to v1.4.2 manually since it was taking a little while for the new version to get to Magento Connect.

I setup the plugin to keep my checkout on my website, so the only time it leaves to go to Amazon is through the popup window when it originally asks me to log into Amazon.

On the checkout page, I select the Address, payment information and then click Place Order.

However I get a window saying: "Please check shipping address information. Please enter the first name. Please enter the last name. Please enter the street."

However, all that information is already there since my Amazon account has that info setup.

I also get the below in my exception.log under /var/log

I use Extendware's Full Page cache which is the "ew" folder you see below.

`
2016-05-18T22:06:48+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Please check shipping address information. Please enter the first name. Please enter the last name. Please enter the street.' in /serverpath/public_html/app/Mage.php:595
Stack trace:
#0 /serverpath/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(298): Mage::throwException('Please check sh...')
#1 /serverpath/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(222): Mage_Sales_Model_Service_Quote->_validate()
#2 /serverpath/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(238): Mage_Sales_Model_Service_Quote->submitNominalItems()
#3 /serverpath/public_html/app/code/community/Amazon/Payments/Model/Type/Checkout.php(210): Mage_Sales_Model_Service_Quote->submitAll()
#4 /serverpath/public_html/app/code/community/Amazon/Payments/controllers/CheckoutController.php(298): Amazon_Payments_Model_Type_Checkout->saveOrder()
#5 /serverpath/public_html/var/cache/ew/files/9a/b9/Mage/Core/Controller/Varien/Action.php(437): Amazon_Payments_CheckoutController->saveOrderAction()
#6 /serverpath/public_html/var/cache/ew/files/c9/2e/Mage/Core/Controller/Varien/Router/Standard.php(273): Mage_Core_Controller_Varien_ActionOverriddenClass->dispatch('saveOrder')
#7 /serverpath/public_html/app/code/local/Extendware/EWOfflineMaintenance/Controller/Override/Mage/Core/Varien/Router/Standard.php(63): Mage_Core_Controller_Varien_Router_StandardOverriddenClass->match()
#8 /serverpath/public_html/var/cache/ew/files/52/17/Mage/Core/Controller/Varien/Front.php(191): Extendware_EWOfflineMaintenance_Controller_Override_Mage_Core_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 /serverpath/public_html/app/code/local/Extendware/EWPageCache/Controller/Override/Mage/Core/Varien/Front.php(17) : eval()'d code(17): Mage_Core_Controller_Varien_FrontOverriddenClass->dispatch()
#10 /serverpath/public_html/app/code/core/Mage/Core/Model/App.php(365): Extendware_EWPageCache_Controller_Override_Mage_Core_Varien_Front->dispatch()
#11 /serverpath/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#12 /serverpath/public_html/index.php(83): Mage::run('', 'store')
#13 {main}

`

**Comment by sadeeshameex** [comment]
when i click place order button same issue came

i have use Magento community v 1.9.2.4.

Error Message:

{"success":false,"error":true,"error_messages":"Please check shipping address information. Please enter the first name."}

Pls help me any one 

Thanks,

**Comment by snoroozi** [comment]
Are you sure you are not in developer/sandbox mode?

**Comment by sadeeshameex** [comment]
Yes i have checked with both mode. 

We assume shipping address data is not assign to the quote address object.

**Comment by cryogenn** [comment]
sadeeshameex - thanks for reporting this. Hopefully someone will look into the issue now. Been trying to use Amazon Payments for months but just can't.

**Comment by islandskater43** [comment]
@sadeeshameex Can you confirm whether you are using Extendware's Full Page cache?

**Comment by sadeeshameex** [comment]
No, We are using only Magento cache.

**Comment by islandskater43** [comment]
Additional logging has been added in issue #296. Please upgrade to the latest extension code and provide additional log details if the problem persists.

**Comment by cryogenn** [comment]
Where is the latest extension code? I still only see v1.4.2 at https://github.com/amzn/amazon-payments-magento-plugin/releases which I what I was using all the time to produce the error.
