### ISSUE TITLE
Shipping Method are not loaded

### ISSUE THREAD

**Issue by niceart** [amzn/amazon-payments-magento-plugin#267]
Hello,

we installed version 1.7.6 on Magento CE 1.7.0.2 - everthing is working fine, but in the checkout only the boxes Shipping Method and Payment Method is loaded - the box Shipping Adress and Checkout Overview is still loading. Any ideas?

Thank you for your help...
Andreas

**Comment by islandskater43** [comment]
Hi @niceart - are you sure you installed this version of the plugin? Our highest version is 1.4.2 (available via GitHub) or 1.4.0 (available via Connect).

The version number that you reference makes me think you may be using this:
https://www.magentocommerce.com/magento-connect/login-and-pay-with-amazon-advanced-payment-apis-for-europe.html

**Comment by islandskater43** [comment]
Closing due to no response. Feel free to reopen if necessary.
