### ISSUE TITLE
Mage World Free Gift extension

### ISSUE THREAD

**Issue by FFUSA** [amzn/amazon-payments-magento-plugin#269]
after install the amazon payment the free gift extension stopped working. when i disabled the amazon payment it started working fine again. 
probably has something to do with the scripts running on the view cart page

**Comment by islandskater43** [comment]
@FFUSA - sorry for the delay here - was your cart page previously not secure (served over HTTP)?

**Comment by islandskater43** [comment]
@FFUSA - please reopen if you continue to have this problem and are able to further troubleshoot.
