### ISSUE TITLE
Stores not Storing (un)secure URL in DB

### ISSUE THREAD

**Issue by needplumbingsupplies-git** [amzn/amazon-payments-magento-plugin#271]
Stores not Storing (un)secure URL in DB

There are two locations where I identified that the extension is explicitly looking in the DB for the secure and unsecure url for the given store. This prevents the extension from loading necessary content and is a common configuration among larger Magento installations with active deployment schedules. I have made some amendments to the code in the following files. If you are interested in viewing the differences please let me know.

| File | Class | Change |
| ------------- | ------------- | ------------- |
| Amazon/Payments/Model/SimplePath.php  | Amazon_Payments_Model_SimplePath | Updated the getFormParams() function to check both the DB and pull information from the configuration files. |
| Amazon/Payments/Model/Observer/Action.php  | Amazon_Payments_Model_Observer_Action | Created a constructor class that will collect the DB values and the config file values and set an object level var to use as verification |

EXAMPLE OF CODE UPDATE
```
public function getFormParams()
{
    // Retrieve store URLs from config
    $urls = array();
    $db = Mage::getSingleton('core/resource')->getConnection('core_read');

    $select = $db->select()
        ->from(Mage::getSingleton('core/resource')->getTableName('core_config_data'))
        ->where('path IN (?)', array('web/unsecure/base_url', 'web/secure/base_url'));

    //if there are url records in the DB
    if(!empty($db->fetchAll($select))){
      foreach ($db->fetchAll($select) as $row) {
        if($url = parse_url($row['value']) && isset($url['host'])){
          $urls[] = 'https://' . $url['host'];  
        }else{
          foreach(Mage::app()->getStores() as $store){
            //get active store code
            $storeCode = $store->getCode();
            $url = Mage::getConfig()->getNode('stores/' . $storeCode . '/web/secure/base_url');
            //only add url once using base64 encode
            if(empty($urls[base64_encode($url)])){                    
              $urls[] = Mage::getConfig()->getNode('stores/' . $storeCode . '/web/secure/base_url');
            }
          }
        }
      }
    }

    return array(
        'locale' => Mage::getStoreConfig('general/country/default'),
        'spId' => self::PARAM_SP_ID,
        'allowedLoginDomains[]' => array_unique($urls),
        'spSoftwareVersion' => Mage::getVersion(),
        'spAmazonPluginVersion' => Mage::getConfig()->getModuleConfig("Amazon_Payments")->version,
    );
}
```

**Comment by jonahellison** [comment]
@needplumbingsupplies-git Thanks for the example code. For Action.php, doesn't Mage::getStoreConfig() already load from config files?

**Comment by needplumbingsupplies-git** [comment]
It does in fact. The issue stems from when there isn't a value in the config and the Amazon configuration files are loaded before the local.xml config file. It basically would find an empty value in the DB and assume that was the value it was running with instead of waiting on the updates in the local.xml. I assume this is due to the recursive nature in which Magento loads config files but I didn't dig deeper into the issue once I created the fix :-P
