### ISSUE TITLE
Unable to Deactivate Login with Amazon

### ISSUE THREAD

**Issue by seancase** [amzn/amazon-payments-magento-plugin#272]
Previously, Login with Amazon was able to be deactivated leaving just Pay with Amazon as functional.  This is described in the documentation:
“If you do not want this functionality and want the Amazon buyers to check out as guests, disable Login with Amazon from System->Configuration->Customers->Login with Amazon”

However, the configuration is unified in 1.4.1 and I am unable to see how this is done.

Important for those merchants wishing to avoid the account merger step.

**Comment by anakenabcn** [comment]
Same issue here

**Comment by danielneu** [comment]
@islandskater43 is this something we can have added back shortly?
