### ISSUE TITLE
Problem using onestepcheckout

### ISSUE THREAD

**Issue by rodrigobalero** [amzn/amazon-payments-magento-plugin#274]
Hey guys,

We are implementing on our store the Amazon Payment, but when I try to do a normal checkout without click in pay whit amazon this erros appear:

`Invalid method Mage_Core_Block_Template::isPopup(Array
(
)
)

Trace:
#0 /var/apps/store/app/design/frontend/base/default/template/amazon_payments/script.phtml(22): Varien_Object->__call('isPopup', Array)
#1 /var/apps/store/app/design/frontend/base/default/template/amazon_payments/script.phtml(22): Mage_Core_Block_Template->isPopup()
#2 /var/apps/store/app/code/core/Mage/Core/Block/Template.php(241): include('/var/apps/www.d...')
#3 /var/apps/store/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#4 /var/apps/store/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#5 /var/apps/store/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#6 /var/apps/store/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#7 /var/apps/store/app/code/core/Mage/Core/Block/Abstract.php(577): Mage_Core_Block_Abstract->_getChildHtml('amazon_payments...', true)
#8 /var/apps/store/app/design/frontend/smartwave/porto/template/page/html/head.phtml(38): Mage_Core_Block_Abstract->getChildHtml()
#9 /var/apps/store/app/code/core/Mage/Core/Block/Template.php(241): include('/var/apps/www.d...')
#10 /var/apps/store/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/smartw...')
#11 /var/apps/store/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#12 /var/apps/store/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#13 /var/apps/store/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#14 /var/apps/store/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('head', true)
#15 /var/apps/store/app/design/frontend/smartwave/porto/template/page/1column.phtml(35): Mage_Core_Block_Abstract->getChildHtml('head')
#16 /var/apps/store/app/code/core/Mage/Core/Block/Template.php(241): include('/var/apps/www.d...')
#17 /var/apps/store/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/smartw...')
#18 /var/apps/store/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#19 /var/apps/store/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#20 /var/apps/store/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#21 /var/apps/store/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#22 /var/apps/store/app/code/local/Magestore/Onestepcheckout/controllers/IndexController.php(89): Mage_Core_Controller_Varien_Action->renderLayout()
#23 /var/apps/store/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Magestore_Onestepcheckout_IndexController->indexAction()
#24 /var/apps/store/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#25 /var/apps/store/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#26 /var/apps/store/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#27 /var/apps/store/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#28 /var/apps/store/index.php(83): Mage::run('default', 'store')
#29 {main}`

I tried to set the amazon pay to work in "Amazon Standalone checkout", but the error persists. But, when I tried to use the amazon pay with our onestep checkout disabled it works fine, but the deal here is understand what is wrong and fix it.

Bests,
Balero.

**Comment by bhoudek83** [comment]
Same exact issue here.

**Comment by nitin-prodigi** [comment]
same issue here. Had to disable amazon payment

**Comment by islandskater43** [comment]
@nitin-prodigi  - Can you share which checkout module you are using?

**Comment by jonahellison** [comment]
This can be resolved by upgrading or modifying amazon_payments.xml using the fix committed on 8/15:

https://github.com/amzn/amazon-payments-magento-plugin/commit/c688b48ee7d1b1be82ded074b196227951af35ac#diff-3b561d586b637cc72fe2737674d751c6

**Comment by nitin-prodigi** [comment]
Thanks, sorry didnt see the message, but after some digging, did the exact same thing

**Comment by islandskater43** [comment]
Thanks for confirming @nitin-prodigi!

**Comment by hzubyrss** [comment]
Hey thanks for posting but its not working i tried both Manually update code and update file both way it show same error !

**Comment by ab7** [comment]
I was able fix this error by changing the block type in /app/design/frontend/base/default/layout/onestepcheckout.xml from `core/template` to `amazon_payments/script`.

```xml
<?xml version="1.0"?>
<layout version="0.1.0">
    <onestepcheckout_index_index>
        <reference name="root">
            <action method="setTemplate">
                <template>page/1column.phtml</template>
            </action>
        </reference>
        <reference name="head">
            <!-- Amazon payment-->
            <action method="addJs" ifconfig="payment/amazon_payments/enabled">
                <script>prototype/window.js</script>
            </action>
            <action method="addItem" ifconfig="payment/amazon_payments/enabled">
                <type>js_css</type>
                <name>prototype/windows/themes/default.css</name>
            </action>
            <action method="addItem" ifconfig="payment/amazon_payments/enabled">
                <type>js_css</type>
                <name>prototype/windows/themes/alphacube.css</name>
            </action>
            <action method="addItem" ifconfig="payment/amazon_payments/enabled">
                <type>skin_css</type>
                <name>amazon_payments/css/popup_alphacube.css</name>
                <params/>
            </action>
    --->    <block type="amazon_payments/script" ifconfig="payment/amazon_payments/enabled" name="amazon_payments.script" template="amazon_payments/script.phtml" />
...
```

Might be worth doing a quick codebase search for `template="amazon_payments/script.phtml` and making sure the block type is correct for each instance.

**Comment by hzubyrss** [comment]
Alex Are you using Magestore one step checkout extension ? if yes can you please conform which version ? because i update that code and stile getting same error !

**Comment by hzubyrss** [comment]
Finally i fixed if some one else stile have issue contact me i will help you ! with amazone or any other checkout extension : Skype me Zubypk92

**Comment by elitistdogg** [comment]
@hzubyrss can you share what the fix is?

**Comment by hzubyrss** [comment]
Hi , elitistdogg May i know which one step extension you are using give me link to one step checkout extension page ?

**Comment by elitistdogg** [comment]
I am using the mage store one step checkout like you mentioned in comment
298.
I made a new issue with the exact code error and trace.

Magneto.weddingprepgals.com/onestepcheckout/index

**Comment by hzubyrss** [comment]
Did you tried this solution ? if you are using latest version of magestore checkout then it should work fine >> /app/design/frontend/base/default/layout/onestepcheckout.xml from core/template to amazon_payments/script.

<?xml version="1.0"?>
<layout version="0.1.0">
    <onestepcheckout_index_index>
        <reference name="root">
            <action method="setTemplate">
                <template>page/1column.phtml</template>
            </action>
        </reference>
        <reference name="head">
            
            <action method="addJs" ifconfig="payment/amazon_payments/enabled">
                <script>prototype/window.js</script>
            </action>
            <action method="addItem" ifconfig="payment/amazon_payments/enabled">
                <type>js_css</type>
                <name>prototype/windows/themes/default.css</name>
            </action>
            <action method="addItem" ifconfig="payment/amazon_payments/enabled">
                <type>js_css</type>
                <name>prototype/windows/themes/alphacube.css</name>
            </action>
            <action method="addItem" ifconfig="payment/amazon_payments/enabled">
                <type>skin_css</type>
                <name>amazon_payments/css/popup_alphacube.css</name>
                <params/>
            </action>
    --->    <block type="amazon_payments/script" ifconfig="payment/amazon_payments/enabled" name="amazon_payments.script" template="amazon_payments/script.phtml" />
...
