### ISSUE TITLE
Login Pop-up problem

### ISSUE THREAD

**Issue by joeljv91** [amzn/amazon-payments-magento-plugin#277]
Hi!

We are integrating amazon payments in our eShop and when we are going to login with amazon in pop-up mode the redirect it's not correct.

https://www.myshop.com/checkout/amazon_paymentsaccount/redirect?access_token=Atza%7CIwEBINkwLQmYk37XhjEKB......

This "amazon_paymentsaccount" has to be "amazon_payments/account" no? I'm not sure if there is a bug in the extension or we have a problem with our configuration.

We are in sandbox mode and we only have the option Pop-up to Yes.

Thanks!

**Comment by joeljv91** [comment]
I think I found the origin of this problem.

Is in **Amazon_Payments_Block_Login_Button**, method **getCheckoutUrl**

```
/**
 * Return URL to use for checkout
 */
public function getCheckoutUrl()
{
    return $this->helper('amazon_payments')->getCheckoutUrl() . 'account/redirect'; // <-- / missing at the start of account
}
```

**Comment by islandskater43** [comment]
@joeljv91 - Let me confirm the behavior on a fresh Magento instance. We haven't seen this issue before, so I think it might be a config issue on your side, but let me confirm.

**Comment by joeljv91** [comment]
@islandskater43 - Okey, In the meantime I will try to investigate my site configuration.

**Comment by joeljv91** [comment]
@islandskater43 - I found the problem, it's our fault sorry we have a method which remove every "/" at the end of the url in checkoutUrl.

You can close this issue and thanks 👍 .
