### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by heartlandbr** [amzn/amazon-payments-magento-plugin#278]
Exception during cache and session cleaning: Error in file: "/home/caroli53/public_html/app/code/community/Amazon/Payments/sql/payments_setup/upgrade-1.3.0-1.4.0.php" - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'caroli53_mage654.core_config_data' doesn't exist, query was: SELECT `core_config_data`.\* FROM `core_config_data` WHERE (path IN ('payment/amazon_payments/access_secret', 'payment/amazon_payments/client_secret'))

**Comment by islandskater43** [comment]
Hi @heartlandbr - do you have table base names? If so, can you confirm if you installed via Magento Connect?

**Comment by heartlandbr** [comment]
My database has a prefix.

Sent from my iPhone

On Sep 1, 2016, at 11:41 AM, Matt Neilson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @heartlandbr<https://github.com/heartlandbr> - do you have table base names? If so, can you confirm if you installed via Magento Connect?

-

**Comment by nicklera1** [comment]
Hi @heartlandbr - Was Magento installed using Cpanel?

**Comment by heartlandbr** [comment]
Yes.

Sent from my iPhone

On Sep 1, 2016, at 12:22 PM, nicklera1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @heartlandbr<https://github.com/heartlandbr> - Was Magento installed using Cpanel?

-

**Comment by nicklera1** [comment]
@heartlandbr  - When installing Magento with Cpanel on a site that has no SSL installed (http) Magento installer for security reasons will append random prefix to data tables.

**Comment by heartlandbr** [comment]
What would I need to do to get extension installed.

Sent from my iPhone

On Sep 1, 2016, at 2:05 PM, nicklera1 <notifications@github.com<mailto:notifications@github.com>> wrote:


@heartlandbr<https://github.com/heartlandbr> - When installing Magento with Cpanel on a site that has no SSL installed (http) Magento installer for security reasons will append random prefix to data tables.

-

**Comment by islandskater43** [comment]
@heartlandbr - You should be able to install using the code here in GitHub now, and not be affected by the issue. Or, if you would prefer to install via Magento Connect, we should have an updated version pushed out there shortly. If you'd prefer the Magento Connect route, just let me know and I'll update/close this issue once the new code is pushed out to Magento Connect.

**Comment by islandskater43** [comment]
Path to resolution provided. If there is further support needed, feel free to open a new issue.
