### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by judaschwartz** [amzn/amazon-payments-magento-plugin#279]
`<?php echo $this­>getChildHtml('amazonbutton'); ?>`
[](
https://github.com/amzn/amazon-payments-magento-plugin/wiki/Community-and-FAQ#q-id-like-to-place-the-login-with-amazon-or-pay-with-amazon-buttons-elsewhere-on-my-site-such-as-on-a-product-detail-page)

is missing - $this­>

**Comment by jonahellison** [comment]
@islandskater43 This refers to https://payments.amazon.com/help/201828720

**Comment by islandskater43** [comment]
Thanks @jonahellison for clarifying and @judaschwartz for reporting!

Update has been made, waiting for cache to expire.

**Comment by islandskater43** [comment]
Update is publicly available. Resolving.
