### ISSUE TITLE
ShipStation Phone Number Issue

### ISSUE THREAD

**Issue by vdub02** [amzn/amazon-payments-magento-plugin#281]
We're having an issue where customers who checkout in our Magento store using Amazon pay but don't have a phone number on file with Amazon (or maybe they are deleting it during checkout).  

This creates a situation where the phone number appears in Magento as just a dash (see attached screenshot).  

Then, when this order gets pulled into ShipStation (which is one of the most popular ecommerce shipping providers), it creates an error message due to invalid phone number.

I learned that either the phone number field needs to be completely blank in Magento or a 10-digit phone number (000-000-0000 is even okay).

Is this a setting or something that can be corrected?

**Comment by islandskater43** [comment]
@vdub02 - can you try modifying this line?

https://github.com/amzn/amazon-payments-magento-plugin/blob/master/app/code/community/Amazon/Payments/Helper/Data.php#L344

Instead of '-', pass in '000-000-0000'.

I'll try and validate this as well.

**Comment by islandskater43** [comment]
I'm not 100% certain what magento is expecting as an input here (hyphens stripped?). The XML response from GetOrderReferenceDetails looks like this: `<Phone>800-000-0000</Phone>`
If magento doesn't care, then we should be able to make the change I recommended above.
