### ISSUE TITLE
JQuery Conflict Render Unusable

### ISSUE THREAD

**Issue by snoroozi** [amzn/amazon-payments-magento-plugin#284]
We used amazon payments on production daily.  After updating magento and ultimo theme to the latest for 1.9.2.4 the jquery issues make the product unusable as they globally override the variables for the jquery we already load on our site which is a much newer version.

commenting noconflict and resetting the global variable get us nowhere.  Is there a way I can host the script on my server, so I can use our jquery?

We've had to totally disable this plugin for customers.

**Comment by snoroozi** [comment]
Anyone home in here?

**Comment by danielneu** [comment]
Please check if the page is loading the Widgets.js file twice. This is the only known scenario where our jQuery version leaks to the main window.

**Comment by snoroozi** [comment]
Yes it does do that. What's the solution for that?

**Comment by snoroozi** [comment]
It's most prominent on the cart page

**Comment by islandskater43** [comment]
Hey @snoroozi - the script file is intended to only load once. Currently it is designed to load before the body end, per the front-end layout xml. Can you try and change this to before_head_end on line 30 of the layout xml?
https://github.com/amzn/amazon-payments-magento-plugin/blob/master/app/design/frontend/base/default/layout/amazon_payments.xml#L30

**Comment by islandskater43** [comment]
@snoroozi - did the edit suggested fix the issue with jquery conflicts? It's not clear based on your previous comment.

**Comment by snoroozi** [comment]
I've not tested that. I will right now.

**Comment by snoroozi** [comment]
Seemed to work on cart, but account area is screwed up http://www.awesomescreenshot.com/image/1624637/632f61f1bc2e130c4c6c5fc4e9fb4ea3

**Comment by snoroozi** [comment]
Would love to be able to turn back on for customers.

**Comment by islandskater43** [comment]
Hey @snoroozi - when you say screwed up, are you referring to the fact that the Login button appears above the "Login or Create Account" section? Or is the issue the jQuery errors in the console? If the latter, can you see if the widgets.js file is loading twice on that page?

**Comment by snoroozi** [comment]
Yes, i'm sure it's loading twice.  For ultimo, the best solution I've found is to comment out mini cart entirely from the amazon_payments.xml, but that foregoes the option to show on shopping cart.  But overall creates the most stability.

**Comment by islandskater43** [comment]
Can you try modifying this line:
https://github.com/amzn/amazon-payments-magento-plugin/blob/master/app/design/frontend/base/default/layout/amazon_payments.xml#L403

And update "after_body_start" to "before_head_end" and see if it reduces the number of times the script loads from 2 to 1?

**Comment by islandskater43** [comment]
And before you make the above change, any chance you can share the HTML source code for the page? I'd love to see what the duplicated script tag looks like on your instance.

**Comment by snoroozi** [comment]
Matt, send me a personal message with your IP and I can let you view our
dev site

**Comment by snoroozi** [comment]
scottnoroozi@gmail.com

**Comment by snoroozi** [comment]
[results.txt](https://github.com/amzn/amazon-payments-magento-plugin/files/490791/results.txt)

**Comment by jonahellison** [comment]
Removed Widgets.js from loading on every page by default. Added config option to enable minicart button.

**Comment by snoroozi** [comment]
So does this solve the issue with the shopping cart page in ultimo?  Currently we have to keep Amazon button disabled on cart page because of conflict with minicart.  

Which means a lot less people check out with Amazon.
