### ISSUE TITLE
Parser Blocking Script Warning

### ISSUE THREAD

**Issue by snoroozi** [amzn/amazon-payments-magento-plugin#285]
Any resolution for this in chrome console?

A Parser-blocking, cross-origin script, https://api-cdn.amazon.com/sdk/login1.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.

**Comment by islandskater43** [comment]
Thanks @snoroozi - I'm working through this with our teams internally. A fix for this shouldn't require any changes to the plugin. Leaving open until I receive confirmation about our path forward.

https://developers.google.com/web/updates/2016/08/removing-document-write

**Comment by islandskater43** [comment]
![image](https://cloud.githubusercontent.com/assets/1476371/19006561/047f3a0e-8715-11e6-9165-d93e4a9552bd.png)

**Comment by snoroozi** [comment]
?

**Comment by ivantedja** [comment]
@islandskater43 any update on this one?

**Comment by danielneu** [comment]
Hi,

this is something we can circumvent in the module, created #292 for this.
We are also addressing this internally for a general solution.

Closing this one in favor of #292
