### ISSUE TITLE
Customer verify redirect to empty cart

### ISSUE THREAD

**Issue by joeljv91** [amzn/amazon-payments-magento-plugin#287]
Hi

When a customer exists in magento and we try to login with amazon with the same email, we need to verify our magento account. In "amazon_payments/customer/verify" I can see this parameter "?redirect=checkout/amazon_payments" so when the user verify her account will be redirected to an empty cart.

Why is redirecting to empty cart instead of customer account?

**Steps to replicate**
1. Create customer account in magento with email "test@email.com"
2. Login with amazon buyer created in sandbox with the same email "test@email.com"
3. In the verify page, verify your magento account.

**Results**

User is redirected to empty cart.

Thanks!

**Comment by jonahellison** [comment]
Fixed redirect URL to customer/account if logging in from account page (this issue occurred when Amazon_Login was merged with Amazon_Payments).
