### ISSUE TITLE
Is it possible to check out at Default Display Currency?

### ISSUE THREAD

**Issue by lizenial** [amzn/amazon-payments-magento-plugin#289]
Hello,

Appreciate your great works!

It looks like the customer can check out at Base Currency only.
How can I configure the customer can check out at Default Display Currency, Not Base Currency?

Thank you!

**Comment by islandskater43** [comment]
@lizenial - to circle back on this, it's not possible. This is mainly due to the restriction with a Pay with Amazon account only being enabled to transact in one currency. Making this change would cause API errors.
