### ISSUE TITLE
JS failing to Serialize form during SaveOrder function call

### ISSUE THREAD

**Issue by nicklera1** [amzn/amazon-payments-magento-plugin#293]
During SaveOrder call there is an issue with Serialization if Agreement form exists. var params become a string and not an object as per my screenshot.
![screen shot 2016-11-07 at 1 02 07 pm](https://cloud.githubusercontent.com/assets/20075335/20075908/1106a41c-a4eb-11e6-8ab6-c87a7c98a14c.png)

Posible solution working example here:
http://jsbin.com/pumapuheje/1/edit?html,js,output

Thank you.

**Comment by islandskater43** [comment]
@nicklera1 - can you please reach out to the merchant and confirm if the commit (https://github.com/amzn/amazon-payments-magento-plugin/commit/28b20b4f179903dfe97cc8b46479c1b056555022) resolves the issue?
