### ISSUE TITLE
Feature: Ability to add Coupon/Discount Code Field on Amazon Standalone Checkout

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-plugin#294]
As a merchant, I want to have the ability to add coupon code functionality to the Amazon Standalone checkout flow.

**Comment by gbear** [comment]
Message: to get user back to cart to use coupon code.

**Comment by jonahellison** [comment]
Added "Discount Codes" coupon block to standalone checkout. Also added "Show Coupon" config to hide coupon block.
