### ISSUE TITLE
Amazon Payments Diagnostics tool throwing exception

### ISSUE THREAD

**Issue by nicklera1** [amzn/amazon-payments-magento-plugin#295]
While running Diagnostics tool we see this exception thrown.
![screen shot 2016-11-14 at 10 30 39 am](https://cloud.githubusercontent.com/assets/20075335/20277639/3c4111b0-aa56-11e6-8d99-2646b3c62366.png)

**Comment by jonahellison** [comment]
Fixed PHP warning.

**Comment by islandskater43** [comment]
@nicklera1 - can you work with the affected merchant to confirm this fix resolves the issue?
