### ISSUE TITLE
magestore one step checkout extension not working (follow up to #298)

### ISSUE THREAD

**Issue by elitistdogg** [amzn/amazon-payments-magento-plugin#301]
I am trying to reopen this as the fix from the previous thread about the Mage Store One Step Checkout is not working.
Invalid method Mage_Core_Block_Template::isEnabled(Array
(
)
)

Trace:
#0 /home/wpgftp/public_html/magento/app/design/frontend/base/default/template/amazon_payments/script.phtml(12): Varien_Object->__call('isEnabled', Array)
#1 /home/wpgftp/public_html/magento/app/design/frontend/base/default/template/amazon_payments/script.phtml(12): Mage_Core_Block_Template->isEnabled()
#2 /home/wpgftp/public_html/magento/app/code/local/Mage/Core/Block/Template.php(322): include('/home/wpgftp/pu...')
#3 /home/wpgftp/public_html/magento/app/code/local/Mage/Core/Block/Template.php(355): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#4 /home/wpgftp/public_html/magento/app/code/local/Mage/Core/Block/Template.php(369): Mage_Core_Block_Template->renderView()
#5 /home/wpgftp/public_html/magento/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#6 /home/wpgftp/public_html/magento/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#7 /home/wpgftp/public_html/magento/app/code/core/Mage/Core/Block/Abstract.php(577): Mage_Core_Block_Abstract->_getChildHtml('amazon_payments...', true)
#8 /home/wpgftp/public_html/magento/app/design/frontend/base/default/template/page/html/head.phtml(43): Mage_Core_Block_Abstract->getChildHtml()
#9 /home/wpgftp/public_html/magento/app/code/local/Mage/Core/Block/Template.php(322): include('/home/wpgftp/pu...')
#10 /home/wpgftp/public_html/magento/app/code/local/Mage/Core/Block/Template.php(355): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#11 /home/wpgftp/public_html/magento/app/code/local/Mage/Core/Block/Template.php(369): Mage_Core_Block_Template->renderView()
#12 /home/wpgftp/public_html/magento/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#13 /home/wpgftp/public_html/magento/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#14 /home/wpgftp/public_html/magento/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('head', true)
#15 /home/wpgftp/public_html/magento/app/design/frontend/minimalism/default/template/page/1column.phtml(17): Mage_Core_Block_Abstract->getChildHtml('head')
#16 /home/wpgftp/public_html/magento/app/code/local/Mage/Core/Block/Template.php(322): include('/home/wpgftp/pu...')
#17 /home/wpgftp/public_html/magento/app/code/local/Mage/Core/Block/Template.php(355): Mage_Core_Block_Template->fetchView('frontend/minima...')
#18 /home/wpgftp/public_html/magento/app/code/local/Mage/Core/Block/Template.php(369): Mage_Core_Block_Template->renderView()
#19 /home/wpgftp/public_html/magento/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#20 /home/wpgftp/public_html/magento/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#21 /home/wpgftp/public_html/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#22 /home/wpgftp/public_html/magento/app/code/local/Magestore/Onestepcheckout/controllers/IndexController.php(77): Mage_Core_Controller_Varien_Action->renderLayout()
#23 /home/wpgftp/public_html/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Magestore_Onestepcheckout_IndexController->indexAction()
#24 /home/wpgftp/public_html/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#25 /home/wpgftp/public_html/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#26 /home/wpgftp/public_html/magento/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#27 /home/wpgftp/public_html/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#28 /home/wpgftp/public_html/magento/index.php(83): Mage::run('', 'store')
#29 {main}

**Comment by islandskater43** [comment]
Resolved by https://github.com/amzn/amazon-payments-magento-plugin/issues/298#issuecomment-270675051
