### ISSUE TITLE
Version 1.4.0 is still the latest version available in Magento Connect

### ISSUE THREAD

**Issue by jasonnehf** [amzn/amazon-payments-magento-plugin#310]
Hello,

Has there been any progress with updating Magento Connect with the latest (1.4.2) release of this extension? 

It's been almost a year since 1.4.2 was released, and while someone claimed to be working posting it to Magento Connect six months ago (#278), I can't imagine it's still taking this long. 

I'd manually install it, but my company has a troublesome policy on installing Magento plugins manually: _Don't_. _**Ever**_.

Please update Magento Connect with version 1.4.2!

Thank you! We poor Magento folk appreciate it! :)

**Comment by islandskater43** [comment]
Hey @jasonnehf - Sorry for the delay, just released v1.4.4 to Magento Connect, and also released the same on GitHub.

https://github.com/amzn/amazon-payments-magento-plugin/releases/tag/v1.4.4
