### ISSUE TITLE
Your session has expired. Please sign in again by clicking ...

### ISSUE THREAD

**Issue by arnoldmontiel** [amzn/amazon-payments-magento-plugin#316]
Hi
I'm trying to use the plugin in a magento 1.9.3.1, I've installed it and it works fine in a ubuntu 16.04 in a centos release-7-3, then when we went to the productive server with a centos release-6-8 we are able to login but we can not pay with amazon, we only get "Your session has expired. Please sign in again by clicking on the Pay with Amazon Button" into the widgets, it is the same code and same configuration. What can I do to move forward with this problem?

PHP Version 5.6.30
Apache/2.2.15

Thank you very much

**Comment by islandskater43** [comment]
This sounds like a possible whitelist issue with Login with Amazon. Can you confirm that your production domain is whitelisted as an "Allowed JavaScript Origin" in your Login with Amazon application?

The following help topic will guide you on how to confirm this: [Adding allowed JavaScript origins or allowed return URLs](https://pay.amazon.com/us/developer/documentation/lpwa/201956540)

**Comment by murich** [comment]
I have this issue and my domain is in the list of origins
