### ISSUE TITLE
Missing file "amazon_payments_async_decline.html" on composer installation 

### ISSUE THREAD

**Issue by Ben-Gee** [amzn/amazon-payments-magento-plugin#317]
Hi everybody,

whe I try to install this module via composer it always gets me the error 
" [ErrorException]                                                                                                                                                                           
  Source ~/Development/Projects/projectName/code/vendor/amzn/amazon-payments-magento-plugin/app/locale/en_US/template/email/amazon_payments_async_decline.html does not exist "

This is because the modman file states that there is such a file, that has to be copied. But in fact that file is missing.

So either the modman file must be adjusted or the file must be provided in this repository.

Cheers,
Benji

**Comment by Ben-Gee** [comment]
Sorry,
I see now that this is only a problem with the last official release. This problem is not with the current master branch.
So maybe it's wise to create a new release with the lastest code?

Cheers,
Benji

**Comment by islandskater43** [comment]
Thanks @Ben-Gee -- the release is forthcoming. I'll close once it's pushed.

**Comment by islandskater43** [comment]
@Ben-Gee - just released v1.4.4 to Magento Connect, and also released the same on GitHub.

https://github.com/amzn/amazon-payments-magento-plugin/releases/tag/v1.4.4
