### ISSUE TITLE
Difference Between This Extension and the CreativeStyle one?

### ISSUE THREAD

**Issue by sprankhub** [amzn/amazon-payments-magento-plugin#323]
Under https://pay.amazon.com/de/sp/magento, another extension is linked - an extension from CreativeStyle, which seems to be different (https://www.magentocommerce.com/magento-connect/amazon-pay-and-login-with-amazon-for-europe.html). What is the difference between your extension and the one from CreativeStyle? Why are there two extensions? Which one am I supposed to use?

**Comment by danielneu** [comment]
Hi,

this extension is intended to be used on the US market - USD is the by default only supported currency.
The CreativeStyle extension supports the currencies EUR and GBP.

Both extensions are approved and fully supported.
Hope this helps.

Best wishes 
Daniel

**Comment by sprankhub** [comment]
Thanks for clarifying! It may be a good idea to state that in the readme.

**Comment by islandskater43** [comment]
We can definitely do that.
