### ISSUE TITLE
Amazon Logs under System in backend show 404

### ISSUE THREAD

**Issue by andidhouse** [amzn/amazon-payments-magento-plugin#332]
Amazon Log pages which can be accessed via the backed  show both 404 error pages.

domain/admin/amazonlogs/download/clientLog/key/3870fc18a7c3bd0115ec6ef2686a4f06740bce9b0ef2e1d2483a3f82d306b589/

I also wonder why logs are placed in such a section - in my opinion these should be accessible only in the extension tab not to overload the backend totally.

**Comment by islandskater43** [comment]
Hey @andidhouse - can you confirm whether this issue was for our M1 or M2 extension? This sounds like an issue we recently identified on our M2 extension.

https://github.com/amzn/amazon-payments-magento-2-plugin/issues/178

**Comment by islandskater43** [comment]
We think this is definitely for the M2 extension, based on the URL provided. Closing this in lieu of the issue in the M2 repo. https://github.com/amzn/amazon-payments-magento-2-plugin/issues/178
