### ISSUE TITLE
The standard checkout page is not accessible

### ISSUE THREAD

**Issue by kavw** [amzn/amazon-payments-magento-plugin#333]
Hello, I've added the extension with default configuration to an empty magento installation and found the strange behaviour.
If a customer clicks Amazon Pay on the cart page at least one time, he will not be able to access the standard checkout page within the same session.
I'm always redirected to the amazon checkout page when click "proceed checkout". So I can't use PayPal or credit card payment option for example.
Is it a bug or feature? How could it be fixed? 
Thank you in advance.

**Comment by islandskater43** [comment]
Hi @kavw  - sorry for missing this earlier. The behavior you describe is a feature. The way this is designed to work is that if the customer has already logged into Amazon Pay, they will automatically be served the Amazon Pay checkout experience, regardless of whether they click an "Amazon Pay" button to initiate checkout, or they click the "Proceed to Checkout" button. 

Please reopen this issue if you have any further questions.
