### ISSUE TITLE
Amazon pay button is not visible

### ISSUE THREAD

**Issue by balwant20** [amzn/amazon-payments-magento-plugin#341]
In case of Non-Us country, Amazon pay button is not displayed on Cart page.
means onec user come on my website and change country from US to another like spain, then the Amazon pay button is not visible on cart page.
i am using Amazon module-1.2.0 & magento 2.1.7

**Comment by prayagr** [comment]
Hello @balwant20 , thanks for reaching out. Your issue is related to our Magento 2 module, whereas this page is for the Magento 1 module. Can you please create an issue here: https://github.com/amzn/amazon-payments-magento-2-plugin
