### ISSUE TITLE
Amazon Order is not shown in the Backend - But payment completed

### ISSUE THREAD

**Issue by andidhouse** [amzn/amazon-payments-magento-plugin#346]
We have a big problem - sometimes an order is payed via Amazon Pay and this order is not shown in our magento2 system.

In Amazon pay we have the order number 100027565  for the transaction.

In our magento2 shop this order id is missing:

100027564
100027566
100027567

We have no problems with paypal plus or other payment systems so i guess this is related to the extension. Could you guys pls check and make shure that this case is solved in a future version?

Thanks!

**Comment by prayagr** [comment]
Hello @andidhouse , thanks for reaching out. Your issue is related to our Magento 2 module, whereas this page is for the Magento 1 module. Can you please create an issue here: https://github.com/amzn/amazon-payments-magento-2-plugin
