### ISSUE TITLE
Widget.js CHECK_COIN_STATUS_ENDPOINT_ Error in Console

### ISSUE THREAD

**Issue by adamwgriffin** [amzn/amazon-payments-magento-plugin#364]
There seems to be a bug in the Widget.js script. Whenever I include it in my app it does a get request for `/___CHECK_COIN_STATUS_ENDPOINT____/rb/checkStatus`. Since there's no domain at the beginning of the url it's interpreted as a request to my local server, which has no route for this endpoint, so it throws an error.

I'm not sure that this is actually causing an issues with how the script functions. So far it seems to be more of a nuisance than anything. I was asked to look into it so I thought it would be a good idea to open an issue here just in case.

This is the script I'm including. It throws the error even if I never do anything to setup the widget.
```
<script type="text/javascript" src="https://static-na.payments-amazon.com/OffAmazonPayments/us/sandbox/js/Widgets.js" async></script>
```

**Comment by tarishah** [comment]
@adamwgriffin, we are aware and working on this issue. Just an FYI, this is only happening in sandbox and not in production. 

I will update here, once we have resolved this error in sandbox.

**Comment by adamwgriffin** [comment]
Great! Thanks @tarishah

**Comment by tarishah** [comment]
Closing as no longer an issue. Please reach back if there are any further concerns.

Thanks!
