### ISSUE TITLE
Amazon_Payments_Model_SimplePath class relies on mcrypt, which is removed in PHP >= 7.2

### ISSUE THREAD

**Issue by willcodeforfood** [amzn/amazon-payments-magento-plugin#365]
Offending code is here: https://github.com/amzn/amazon-payments-magento-plugin/blob/72d020cdf2f100bae87b81151527254396f37ffe/app/code/community/Amazon/Payments/Model/SimplePath.php#L141

This class looks to be responsible for obtaining API credentials and saving them in the Magento configuration.

**Comment by lemked** [comment]
Dear @willcodeforfood ,

Thanks, we will look into this.

Kind regards,
Daniel

**Comment by lemked** [comment]
Dear @willcodeforfood ,

As Magento 1 is not officially compatible to PHP 7 (and higher), we do not see any reason to remove the dependency on mcrypt either. For reference:
https://devdocs.magento.com/guides/m1x/system-requirements.html

For Magento 2, we also use mcrypt but there is a fallback in place, in case that it is not available.

Closing issue. Feel free to re-open if necessary.

Kind regards,
Daniel

**Comment by willcodeforfood** [comment]
PHP 5.6 will not be PCI compliant next year: [it reaches EoL on Dec 31 2018](http://php.net/supported-versions.php). That means merchants still using Magento 1 will be forced to run it on PHP 7.2.
