### ISSUE TITLE
Amazon Payment button not displayed at the payment method selection - magento

### ISSUE THREAD

**Issue by SawBladeExpress** [amzn/amazon-payments-magento-plugin#366]
If a buyer checks out as a guest, the process works as expected.  If the buyer has signed into their SawBladeExpress account, the button still populates in the cart page and functions as normal.  However, if they go to normal checkout ( not Amazon),  Then on Payment method page Amazon payment is listed as an option  ( Radio Button). When selected it should force or popup to log in to the Amazon account, which does not happen and flow continues to complete the order without selecting any payment method. So one of the two things should happen.
1. Either display the Amazon Payment button next to Amazon payment radio Button ( Payment Methods)
OR
2. On selecting Amazon Payment Radio Button, it should pop up with Amazon account login. If not already logged into Amazon account. The website we are having the problem is at https://sawbladeexpress.com  We are using the plugin for Magento 1.9.3.1 . Will be happy to elaborate more if required.

**Comment by tarishah** [comment]
Hi @SawBladeExpress,

The console error that comes up when the Login and Pay with Amazon radio button is selected is: 
"Uncaught TypeError: Cannot read property 'triggerEvent' of undefined
at HTMLInputElement.eval (eval at (prototype.js:612), :17:55)
at HTMLInputElement.responder (prototype.js:5598)"

this issue can be resolved by making the code change shown in the link here: https://github.com/amzn/amazon-payments-magento-plugin/commit/45187d7a084f0e88a23132b64a6e847b7eceb165

Look forward to hear from you on how this goes.

Tarini S.
Amazon Pay

**Comment by SawBladeExpress** [comment]
Perfect, That worked.  Will this change be made to the Plugin?

**Comment by tarishah** [comment]
Yes, Its in the process to be added to the plugin.

**Comment by SawBladeExpress** [comment]
What version will this be released with? so we can stay updated.

**Comment by tarishah** [comment]
No details yet. Will keep you informed with the version, once its decided.

**Comment by SawBladeExpress** [comment]
okay. thanks a lot we appreciate the quick fix.

**Comment by tarishah** [comment]
No problem! Thanks for using Amazon Pay.
