### ISSUE TITLE
Wallet Widget error: InvalidOrderReferenceId - The OrderReferenceID  is invalid.

### ISSUE THREAD

**Issue by jahanzaibkhanrana** [amzn/amazon-payments-magento-plugin#372]
What I did is just change the setOrderReferenceDetails request parameter "amount", 1st it warned me that you can not change the payment method in open or cancelled state but when i cancelled the transaction from my seller account then, it is not allowing to proceed from my web  
![image](https://user-images.githubusercontent.com/11090008/55706208-0c9fb500-59fa-11e9-8179-18053ddbd2df.png)

**Comment by tarishah** [comment]
Per the issue created at https://github.com/amzn/amazon-pay-sdk-samples/issues/23#event-2259946719, this doesnot seem to be a magento issue.

Closing, please reopen if it is magento related.

Thanks,
Tarini
