### ISSUE TITLE
Checkout progress not showing

### ISSUE THREAD

**Issue by gustavo807** [amzn/amazon-payments-magento-plugin#374]
Hi, 
We have an issue; All checkout progress is not showing during checkout. Everything it's ok with checkout steps but the part of "Your Checkout Progress" it's not showing.

Magento ver. 1.14.0.0
checkout type: Magento Core OnePage Checkout
Amazon plugin: v1.4.4

![image](https://user-images.githubusercontent.com/15847964/58346325-3d0fa700-7e20-11e9-853e-83c1ee4caee1.png)

I was checking on the checkout/onepage.phtml and the getChildHtml('checkoutProgress') is empty
![image](https://user-images.githubusercontent.com/15847964/58346488-b0b1b400-7e20-11e9-9e2e-cb50b792fdc2.png)

**Comment by gustavo807** [comment]
Use getBlockHtml instead getChildHtml in the file Checkout/Onepage.phtml

**Comment by tarishah** [comment]
Fix: Use getBlockHtml instead getChildHtml in the file Checkout/Onepage.phtml
