### ISSUE TITLE
Magento 1.9.4.2 - Session Changes

### ISSUE THREAD

**Issue by mvenghaus** [amzn/amazon-payments-magento-plugin#377]
Hello,

the changes in 
app/code/core/Mage/Checkout/Model/Session.php
after magento update break the module.

When I come with clean cookies and Login via Amazon the Session is renewed. When I try again I always be redirected to customer account. After reverting the Session file everything works as expected.

Any Ideas?

Regards
Marcus

**Comment by tarishah** [comment]
Hello @mvenghaus Thanks for reaching out!

Can you please clarify the issue with exact replication steps? I do not see Session.php file at this location: app/code/core/Mage/Checkout/Model/Session.php in our [plugin](https://github.com/amzn/amazon-payments-magento-plugin/).

**Comment by mvenghaus** [comment]
Hey,

thx for the feedback. 

This file is not from your module. It is a magento core file and is modified by the magento update from 1.9.4.1 to 1.9.4.2. So the newest version of magento makes the problem with your module.

To reproduce just try it with the newest version of magento. Just clean your cookies, add s.th. to your cart and go the amazon checkout. After login the cart is empty.

Regards
Marcus

**Comment by tarishah** [comment]
Thanks @mvenghaus for getting this to our attention. We will look into this. 

Thanks again!

**Comment by tarishah** [comment]
@mvenghaus Would mind trying the fix that we have provided here? This should work, from what we have tested on our end. 

Look forward to hear from you.
Tarini
