### ISSUE TITLE
PSD2 / SCA and Magento Core OnePage Checkout type

### ISSUE THREAD

**Issue by jonesio** [amzn/amazon-payments-magento-plugin#384]
PR #378 added support for PSD2 / Strong Customer Authentication on M1.

Do these changes have any effect for the "Magento Core OnePage Checkout" Checkout type in configuration? It appears with a quick look at the code changes that only the "Amazon Standalone Checkout" type has any changes that reference SCA?

Please confirm @jonahellison.

Thank you!

**Comment by christianzichichi** [comment]
Hi David Jones,

SCA support for the accordion-style checkout will not be supported in M1 US plugin. please find below documentation to install EU M1 plugin that has SCA feature natively embedded:

http://amazon.creativestyle.de/en/latest/
https://marketplace.magento.com/creativestyle-creativestyle-amazonpayments.html

Thanks

Regards

Christian
