### ISSUE TITLE
Add Support for Magento Recurring Billing Profiles

### ISSUE THREAD

**Issue by rjamison** [amzn/amazon-payments-magento-plugin#59]
Add support for Amazon's Automatic Payments feature with Magento's Recurring Billing Profiles.

http://docs.developer.amazonservices.com/en_US/pay_with_amazon_automatic_payments/APAGuide_Introduction.html

**Comment by ngrices** [comment]
Not implementing native recurring billing profiles.

**Comment by rjamison** [comment]
Support for recurring requested in the Q&A in Magento Connect.

**Comment by ngrices** [comment]
@gbear, can we estimate this effort?

**Comment by islandskater43** [comment]
As this is not heavily requested, and the recurring functionality in M1 never left beta, we'll close this feature request for now.
