### ISSUE TITLE
Enable tokenized payments

### ISSUE THREAD

**Issue by ngrices** [amzn/amazon-payments-magento-plugin#61]
Requirement:
1) Direct feedback from digital agency is that merchants want 1-step purchasing
2) Exists on product page
3) Option in admin section 'Turn on one-step purchasing'
4) Only available if 'shortcut on product page' is enabled

Details
1) If the buyer is logged in and the merchant has the shortcut on product page enabled and a new option called "Turn on 1-step purchasing", we should add a 'Buy Now with 1-step' button to the product detail page
2) When clicked, the product should be ordered and the buyer sent to the success page

**Comment by ngrices** [comment]
will release this with the EU deliverables

**Comment by jonahellison** [comment]
For testing:
- Enable Tokenized Payments under Transaction > Advanced Transaction Options
- Perform Amazon Payments checkout with billing agreement selected
- AS ADMIN: create order for customer and select "Login and Pay with Amazon" as payment option to use token
- AS USER: Enable "Shortcut on Product View" and purchase item from product page using token
