### ISSUE TITLE
Chrome on iOS 7 and 8: Login popup does not clear and return to merchant

### ISSUE THREAD

**Issue by ngrices** [amzn/amazon-payments-magento-plugin#64]
Tested with multiple merchants using this extension, on iPhone and iPad using chrome browser with iOS 7x and 8.0
Repro:
1) On chrome for iOS, add something to cart and click Pay with Amazon
2) Popup (new browser window in chrome mobile) appears, enter login credentials
3) Login and agree to consent to share information
4) Login window remains (blank) never returns to merchant site as logged in Amazon buyer

**Comment by endifmedia** [comment]
i know this is an old post, but we are experiencing the same issue with v 1.4.0 of amazon payments magento plugin. was this rolled out the the production version?

**Comment by islandskater43** [comment]
This was fixed in the browser, so no change was needed from the extension side. Can you create a new issue with the details of your current issue? Thanks!
