### ISSUE TITLE
Possible Issue with Compilation Enabled

### ISSUE THREAD

**Issue by rjamison** [amzn/amazon-payments-magento-plugin#89]
Encountered this error, which was resolved by disabling compilation.  

#0 /home/user/domains/website.com/public_html/includes/src/Mage_Adminhtml_Block_System_Config_Form.php(328): Mage::throwException('Invalid config ...') 
#1 /home/user/domains/website.com/public_html/includes/src/Mage_Adminhtml_Block_System_Config_Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element)) 
#2 /home/user/domains/website.com/public_html/includes/src/Mage_Adminhtml_Block_System_Config_Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element)) 
#3 /home/user/domains/website.com/public_html/includes/src/Mage_Adminhtml_Block_System_Config_Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm() 
#4 /home/user/domains/website.com/public_html/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm() 
#5 /home/user/domains/website.com/public_html/includes/src/__default.php(13582): Mage_Adminhtml_System_ConfigController->editAction() 
#6 /home/user/domains/website.com/public_html/includes/src/__default.php(17927): Mage_Core_Controller_Varien_Action->dispatch('edit') 
#7 /home/user/domains/website.com/public_html/includes/src/__default.php(17484): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http)) 
#8 /home/user/domains/website.com/public_html/includes/src/__default.php(20061): Mage_Core_Controller_Varien_Front->dispatch() 
#9 /home/user/domains/website.com/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array) 
#10 /home/user/domains/website.com/public_html/index.php(88): Mage::run('', 'store') 
#11 {main}

Needs some investigation to see if this is reproduceable.

**Comment by ngrices** [comment]
We need to start collecting the ways in which this error manifests. So far I have seen 4 different distinct issues caused by compilation and I expect that it is due to run time class loading differences on different environments.
