### ISSUE TITLE
Support Delayed Authorizations (aka. Pre-Orders)

### ISSUE THREAD

**Issue by rjamison** [amzn/amazon-payments-magento-plugin#92]
A couple of sites have asked for the ability to support a flow where:
* No authorization is performed at checkout, just a confirmed order reference.
* The order is created in the Magento admin with a "pending" status.
* The merchant is able to generate an invoice that creates a new authorize and capture on the confirmed order reference associated with the order.
** In the event the authorize and capture fails, the merchant should see an error message and be able to collect payment via another form.

**Comment by gbear** [comment]
Thinking this could function as a new payment action config:
* authorize only
* authorize & capture (default)
* token only

Token only would create the billing agreement, and create a new Magento order with "processing" status.

Later, the merchant can to the order page, select invoice.  There is process Offline / Online options currently.  If a token exists, would add a "Process via Token" option on the invoice, that would process the auth & capture payment via Amazon Payments and complete the order.

**Comment by rjamison** [comment]
Setting only at global level, will defer item-level config.

**Comment by jonahellison** [comment]
- New global config option under Enable Tokenized Payments: Allow Pre-Orders
- Magento order status defaults to "New Order Status" config
- Invoice creation authorizes and captures (automatically detects if pre-order or not. Order comment also indicates pre-order)
